apiVersion: v1
data:
  DON_TORRENT_BASE_URL: https://dontorrent.review
  DON_TORRENT_TOR_PROXY: http://tor-proxy.arr.svc.cluster.local:8118
  DON_TORRENT_USE_ONION: "true"
  MARCIANO_TORRENT_BASE_URL: https://marcianotorrent.net
  REQUEST_TIMEOUT_MS: "120000"
kind: ConfigMap
metadata:
  labels:
    app: norznab
  name: norznab-config-env
  namespace: arr
