apiVersion: v1
data:
  DON_TORRENT_BASE_URL: https://dontorrent.promo
  HTTP_PROXY: http://gluetun.system.svc.cluster.local:8888
  HTTPS_PROXY: http://gluetun.system.svc.cluster.local:8888
  MARCIANO_TORRENT_BASE_URL: https://marcianotorrent.net
  NO_PROXY: localhost,127.0.0.1,.svc.cluster.local
  NODE_USE_ENV_PROXY: "1"
  REQUEST_TIMEOUT_MS: "20000"
kind: ConfigMap
metadata:
  labels:
    app: norznab
  name: norznab-config-env
  namespace: arr
