apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: norznab
  name: norznab
  namespace: arr
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: norznab
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        name: norznab
    spec:
      containers:
      - env:
        - name: TMDB_API_KEY
          valueFrom:
            secretKeyRef:
              key: TMDB_API_KEY
              name: norznab-sealed-secret
        - name: DON_TORRENT_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: DON_TORRENT_BASE_URL
              name: norznab-config-env
        - name: ENABLE_DON_TORRENT
          valueFrom:
            configMapKeyRef:
              key: ENABLE_DON_TORRENT
              name: norznab-config-env
        - name: ENABLE_MARCIANO_TORRENT
          valueFrom:
            configMapKeyRef:
              key: ENABLE_MARCIANO_TORRENT
              name: norznab-config-env
        - name: MARCIANO_TORRENT_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: MARCIANO_TORRENT_BASE_URL
              name: norznab-config-env
        - name: REQUEST_TIMEOUT_MS
          valueFrom:
            configMapKeyRef:
              key: REQUEST_TIMEOUT_MS
              name: norznab-config-env
        image: ghcr.io/danielramosacosta/norznab:main-0713f4a
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 30
          tcpSocket:
            port: 3000
          timeoutSeconds: 5
        name: norznab
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 3000
          timeoutSeconds: 5
