apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: norznab
  name: norznab-sealed-secret
  namespace: arr
spec:
  encryptedData:
    TMDB_API_KEY: AgAJC3yw3JYRrt+qHBQkz/h3/4m/61Mg5tk1oVmIONtnqdnZC21wlZLMZWXFntBRN15zFYQQutP7nEr7RyX5slf/OGfAqXUUC/pezT0eCywnD0DxvDPBO5fJ4I+zEtuuPHPzdu9H8CbqnBmnmb22s6o/jTzd2rylAOtkKSyPDS+oHuMGmgkIyg5h29VMKN2ws8eaoE+fY/omX4xu62JIPqgXh250QROMAmISreyTthSR4YRMItxY3iBq+m2LyW1QEg/6R21EN+e/Hpkh2IQA+TTmi+Ma6wJI6i6z1HH3VT4YQ36KjlV9VjsHG01q69G7OpfODF0sq5pV/Fe8/yjuXTWSyIF/Cth+SXL7ZMgqIWh5gPqRxSqoh0SVOOel+Hn1tIJlZ5+bFrTeiiU+GVsCD3twJFApQTOq+xAF1PhJ71REejdTWfY7zabZ9FUp4qnHoSoK1itbFda/pHoGFbKdXe/sq33EPYCqeOB/BOmlz9fZJK1BvMgINsVokl1Zs62jfmCCxHGxiU6xLisbrIq8noljRNOSXdfp3FG3fm1i/u1FqVUOC27bg1kvU5La1yXm79/wPrn3WeV2lZJDyqZtV6ax7x39ZsWqOSVaar7G9TzAv90nYMPhdJbLm9kCR5HfvMp4j2MBLJHN3NQ+gWwVfjJy+54j7VAz45BsyVJnVmb/rbGNtvpi6MkCaqB3icvC0KPEwiQt7dAlJgnUafDmx7szICUG/dEw15BKCzn5hUbjvWo6leSFtR3khNL/nfgWeviND0om+gUrzoW8NWFk9sEjuQCDfCI4nWUjDvgnBueB3Ml7QnmlD0mLSzAGaS/E7mE2eLGRXIyVEdUI+5UmoZnqZnwD/k5MsIquXI8hf4KSirMGCznaLToMgtrP+oyWkqQVwj6yxhgWCkus++JDQR73/TfB/H4PBLzmgLMU2q26VLc8Cru1BCU4moP0WnqFq9v2oVoPt6ZFACLfICiXNctlz2HycF2ptujXn8z2qaU2nOgAs7rFUsG2sbD/sA2G/Q==
