apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: monitoringExporters
  name: smartctl-exporter
  namespace: monitoring
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      name: smartctl-exporter
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        name: smartctl-exporter
    spec:
      containers:
      - image: quay.io/prometheuscommunity/smartctl-exporter:v0.14.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 30
          tcpSocket:
            port: 9633
          timeoutSeconds: 5
        name: smartctl-exporter
        ports:
        - containerPort: 9633
          name: smartctl
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 9633
          timeoutSeconds: 5
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
          runAsGroup: 0
          runAsUser: 0
        volumeMounts:
        - mountPath: /dev
          name: dev
        - mountPath: /run/udev
          name: run-udev
          readOnly: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /dev
          type: Directory
        name: dev
      - hostPath:
          path: /run/udev
          type: Directory
        name: run-udev
  updateStrategy:
    type: RollingUpdate
