apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: monitoringExporters
  name: nut-exporter-sealed-secret
  namespace: monitoring
spec:
  encryptedData:
    NUT_EXPORTER_PASSWORD: AgCZOoXB1blu3NI0M2bOYGnADgvWI5fCLNFL6GZc4Q6T18+MM/M9GA2eERCFWT4cUU78N1nA2BKVrwk6/SxzkVwf0XVepXXFYnPvj3CyTYleWoALpV54t+JKGhy+W+uINAYxM84MsZTdS402v9hMhk3eSglHVsDrKTqQh9ABnkKY8n91JqC68uvAuTPwbI8tFB2FTGrH2MiW6ETo3x/h0Ax3b66idjI4KrfKYgmpEt76d/DsRQ4Xez5wRnMVVoMqMVAHYRcwfvlOolt/UJSm3eq6rw7XZo0CQc6d1iODrNkYg2IV8tRRoZPkUx1/ZLvIGCCiK69Pb9+FstF5fofkgoUYnqLoNvTy0FIfVUC5Dj5Uishh69m79QAHLMi6+RmkYt4RvakJp0GUfFKtw04yzP3yyqBbr6ZnuCRdV9LpvYuKP/GTm6b+UCOcvuB9D6GQL7CC+8xCS9abkf3Jt6rUOSnFUKrKz/xLIv3HH/kuH2h6YTvVJQ/Z3u9qhsJYKVQHI0j5uYZr5dBFrdBX/FXusnZrUL/rTpzaKYi8jXWXmvKlBlc+murJpRg/y74II+9D0i3Dvi8web4A0bD57huunJZOSEFDJzd7s423+pDFQKti0dwcAdXSu/XM5BhP9ZHgdHPNxk6sr6wovcN7JyoTcKMOes0uy+nfAqylQnpEhT4+ARzfc/OKQFp7RcFZbQiTHk00HSZ9rqlc6jg+heUcyw==
