apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: synapse
  name: synapse
  namespace: communications
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: synapse
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        name: synapse
    spec:
      containers:
      - env:
        - name: SYNAPSE_CONFIG_PATH
          value: /config/homeserver.yaml
        image: ghcr.io/element-hq/synapse:v1.155.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /_matrix/client/versions
            port: 8008
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
        name: synapse
        ports:
        - containerPort: 8008
          name: http
        - containerPort: 9090
          name: metrics
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /_matrix/client/versions
            port: 8008
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /_matrix/client/versions
            port: 8008
            scheme: HTTP
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /keys/signing.key
          name: signing-key-sealed-secret
          subPath: signing.key
        - mountPath: /media
          name: media
        - mountPath: /data
          name: data
      enableServiceLinks: false
      initContainers:
      - command:
        - /bin/sh
        - -c
        - envsubst < /tpl/homeserver.yaml > /config/homeserver.yaml
        env:
        - name: FORM_SECRET
          valueFrom:
            secretKeyRef:
              key: FORM_SECRET
              name: synapse-sealed-secret
        - name: MACAROON_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: MACAROON_SECRET_KEY
              name: synapse-sealed-secret
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: OIDC_CLIENT_ID
              name: synapse-sealed-secret
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: OIDC_CLIENT_SECRET
              name: synapse-sealed-secret
        - name: REGISTRATION_SHARED_SECRET
          valueFrom:
            secretKeyRef:
              key: REGISTRATION_SHARED_SECRET
              name: synapse-sealed-secret
        - name: SYNAPSE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SYNAPSE_DB_PASSWORD
              name: synapse-db-sealed-secret
        image: docker.io/bhgedigital/envsubst:v1.0-alpine3.6
        imagePullPolicy: IfNotPresent
        name: config-init
        volumeMounts:
        - mountPath: /tpl/homeserver.yaml
          name: synapse-homeserver-tpl
          subPath: homeserver.yaml
        - mountPath: /config
          name: config
      volumes:
      - configMap:
          name: synapse-homeserver-tpl
        name: synapse-homeserver-tpl
      - emptyDir: {}
        name: config
      - name: signing-key-sealed-secret
        secret:
          secretName: signing-key-sealed-secret
      - hostPath:
          path: /cold-data/synapse/media
        name: media
      - emptyDir: {}
        name: data
