apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: synapse
  name: signing-key-sealed-secret
  namespace: communications
spec:
  encryptedData:
    signing.key: AgB/cY0Uot+MIeK6GoiE0nL5JyoLcEd2dhvaZFh8orfyPat9M3j/v5UcBOjx2yVzyqqypkneAsGvVALAslOmp7/XkpTwsq4DOUWQRDcy4JgakFgT/2K8kXjwWXQ/1y4MlZpKgfSQ1Mcrtd8e5BbhIBX6j9mz173Yy+NuKfWESrlAHH73P8eKOunc30l52YpFijmRXX3Sh94pOITF9E82v8cRiWgp0cKyIyWNc8akdfoU4rUEMTKx5W9mz6do8gxozuWRAcgWWVGjOC7PwebkF9oxDLfG0bGqJML7+xDeX928JrwUfKk8EICumaERF7KypzjsvDIgiORLfXT2L7UEW9cbY9wXtEFEOOr25T74Dn7HkRm71dWMI8XyAZRnteJjA/4VdFYDIKuKbzgLhH0bZJW/MWXfLMfaTAD/gIsevuiWagO/BZti4nMjIbQpkSPYZrLpA8RsrZqS0I294kuRafJupyCWzXpAZAu8VVHufKTspgmSj7UTyzjS/UnacahiEpj4Y/sRJGF9J9lKz6k2W/I6WfpkWv0TRiCBLnpORejmYyQTV6CZV+EKCM9eOFxvBtEl78ltRm4DKzHldq0yW4eNgf+k9Itbr8v1qLZhIME3aIDbpDvM30nF+da5lGpkyhwBmHdjD66f/Qw4GXYJYMpx3NtkagiG3wS3fz4UrDSTgGzsh5zIRmQQ3ewLFXj+SqR0SRQtzAwHaIA+lFan4oh/22/WLDRANBCovt/5b/Blo5G3Bd4/E6bN6DlXyygrNP2hThPU49fvZ4l9fA==
