apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: loki
  name: loki-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /data/loki/data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
