apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: loki
  name: loki-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
  volumeName: loki-pv
