apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: sonarr
  name: sonarr
  namespace: arr
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sonarr
  template:
    metadata:
      labels:
        name: sonarr
    spec:
      containers:
      - env:
        - name: PGID
          valueFrom:
            configMapKeyRef:
              key: PGID
              name: sonarr-config-env
        - name: PUID
          valueFrom:
            configMapKeyRef:
              key: PUID
              name: sonarr-config-env
        - name: SONARR__LOG__CONSOLEFORMAT
          valueFrom:
            configMapKeyRef:
              key: SONARR__LOG__CONSOLEFORMAT
              name: sonarr-config-env
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: sonarr-config-env
        - name: UMASK
          valueFrom:
            configMapKeyRef:
              key: UMASK
              name: sonarr-config-env
        image: ghcr.io/hotio/sonarr:release-4.0.16.2944
        imagePullPolicy: IfNotPresent
        name: sonarr
        ports:
        - containerPort: 8989
          name: http
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: data
      volumes:
      - hostPath:
          path: /data/arr/sonarr
        name: config
      - hostPath:
          path: /cold-data/media
        name: data
  updateStrategy:
    type: RollingUpdate
