apiVersion: v1
kind: Service
metadata:
  labels:
    app: jdownloader
    name: jdownloader
  name: jdownloader
  namespace: arr
spec:
  ports:
  - name: jdownloader-web
    port: 5800
    targetPort: 5800
  - name: jdownloader-myjd
    port: 3129
    targetPort: 3129
  selector:
    name: jdownloader
