apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8011"
    prometheus.io/scrape: "true"
  labels:
    app: deluge-exporter
    name: deluge-exporter
  name: deluge-exporter
  namespace: monitoring
spec:
  ports:
  - name: deluge-exporter-metrics
    port: 8011
    targetPort: 8011
  selector:
    name: deluge-exporter
