apiVersion: v1
kind: Service
metadata:
  labels:
    app: victoriametrics
    name: victoriametrics
  name: victoriametrics
  namespace: monitoring
spec:
  ports:
  - name: victoriametrics-http
    port: 8428
    targetPort: 8428
  selector:
    name: victoriametrics
