apiVersion: v1
data:
  configuration.yml: "# yaml-language-server: $schema=https://www.authelia.com/schemas/v4.39/json-schema/configuration.json\n\ntelemetry:\n
    \ metrics:\n    enabled: true\n\nlog:\n  format: 'json'\n  level: 'debug'\n\nauthentication_backend:\n
    \ password_reset:\n    disable: true\n  file:\n    path: /config/users_database.yml\n\nstorage:\n
    \ encryption_key: '{{ env `AUTHELIA_STORAGE_ENCRYPTION_KEY` }}'\n  postgres:\n
    \   address: 'tcp://postgres.databases.svc.cluster.local:5432'\n    username:
    authelia\n    password: '{{ env `AUTHELIA_STORAGE_POSTGRES_PASSWORD` }}'\n    database:
    authelia\n\naccess_control:\n  default_policy: two_factor\n\nsession:\n  secret:
    '{{ env `AUTHELIA_SESSION_SECRET` }}'\n  cookies:\n    - domain: danielramos.me\n
    \     authelia_url: 'https://auth.danielramos.me'\n      default_redirection_url:
    'https://photos.danielramos.me'\n\nnotifier:\n  smtp:\n    address: 'smtp://smtp.eu.mailgun.org:587'\n
    \   username: 'nas@mail.danielramos.me'\n    password: '{{ env `AUTHELIA_NOTIFIER_SMTP_PASSWORD`
    }}'\n    sender: \"NAS <nas@mail.danielramos.me>\"\n    subject: \"[NAS] {title}\"\n\ndefinitions:\n
    \ user_attributes:\n    sftpgo_role:\n      expression: 'username == \"admin\"
    ? \"admin\" : \"user\"'\n\nidentity_providers:\n  oidc:\n    cors:\n      endpoints:\n
    \       - authorization\n        - pushed-authorization-request\n        - token\n
    \       - revocation\n        - introspection\n        - userinfo\n      allowed_origins_from_client_redirect_uris:
    true\n\n    jwks:\n      - key_id: main\n        algorithm: RS256\n        key:
    {{ secret \"/config/secrets/oidc/jwks/rsa.2048.key\" | mindent 10 \"|\" | msquote
    }}\n\n    claims_policies:\n      grafana:\n        id_token: ['email', 'name',
    'groups', 'preferred_username']\n\n      sftpgo:\n        id_token: ['username',
    'sftpgo_role']\n        custom_claims:\n          username:\n            attribute:
    username\n          sftpgo_role:\n            attribute: sftpgo_role\n\n      booklore:\n
    \       id_token: ['email', 'email_verified', 'preferred_username', 'name']\n\n
    \   scopes:\n      sftpgo:\n        claims:\n          - username\n          -
    sftpgo_role\n    \n    clients:\n      - client_id: '{{ env `IDENTITY_PROVIDERS_OIDC_CLIENTS_IMMICH_CLIENT_ID`
    }}'\n        client_name: Immich\n        client_secret: '{{ env `IDENTITY_PROVIDERS_OIDC_CLIENTS_IMMICH_CLIENT_SECRET_DIGEST`
    }}'\n        public: false\n        authorization_policy: two_factor\n        consent_mode:
    'auto'\n        require_pkce: false\n        pkce_challenge_method: ''\n        redirect_uris:\n
    \         - 'https://photos.danielramos.me/auth/login'\n          - 'https://photos.danielramos.me/user-settings'\n
    \         - 'app.immich:///oauth-callback'\n        scopes:\n          - openid\n
    \         - profile\n          - email\n        response_types:\n          - code\n
    \       grant_types:\n          - authorization_code\n        access_token_signed_response_alg:
    none\n        userinfo_signed_response_alg: none\n        token_endpoint_auth_method:
    client_secret_post\n      \n      - client_id: '{{ env `IDENTITY_PROVIDERS_OIDC_CLIENTS_SFTPGO_CLIENT_ID`
    }}'\n        client_name: SFTPGo\n        client_secret: '{{ env `IDENTITY_PROVIDERS_OIDC_CLIENTS_SFTPGO_CLIENT_SECRET_DIGEST`
    }}'\n        public: false\n        authorization_policy: two_factor\n        claims_policy:
    sftpgo\n        consent_mode: 'auto'\n        require_pkce: false\n        pkce_challenge_method:
    ''\n        redirect_uris:\n          - 'https://cloud.danielramos.me/web/oidc/redirect'\n
    \       scopes:\n          - openid\n          - profile\n          - email\n
    \         - sftpgo\n        response_types:\n          - code\n        grant_types:\n
    \         - authorization_code\n        access_token_signed_response_alg: none\n
    \       userinfo_signed_response_alg: none\n        token_endpoint_auth_method:
    client_secret_post\n\n      - client_id: '{{ env `IDENTITY_PROVIDERS_OIDC_CLIENTS_GRAFANA_CLIENT_ID`
    }}'\n        client_name: Grafana\n        client_secret: '{{ env `IDENTITY_PROVIDERS_OIDC_CLIENTS_GRAFANA_CLIENT_SECRET_DIGEST`
    }}'\n        public: false\n        authorization_policy: two_factor\n        claims_policy:
    grafana\n        consent_mode: 'auto'\n        require_pkce: true\n        pkce_challenge_method:
    'S256'\n        redirect_uris:\n          - 'https://grafana.danielramos.me/login/generic_oauth'\n
    \       scopes:\n          - openid\n          - profile\n          - email\n
    \         - groups\n        response_types:\n          - code\n        grant_types:\n
    \         - authorization_code\n        access_token_signed_response_alg: none\n
    \       userinfo_signed_response_alg: none\n        token_endpoint_auth_method:
    client_secret_basic\n\n      - client_id: '{{ env `IDENTITY_PROVIDERS_OIDC_CLIENTS_GITEA_CLIENT_ID`
    }}'\n        client_name: Gitea\n        client_secret: '{{ env `IDENTITY_PROVIDERS_OIDC_CLIENTS_GITEA_CLIENT_SECRET_DIGEST`
    }}'\n        public: false\n        authorization_policy: two_factor\n        #
    See:\n        # * https://github.com/go-gitea/gitea/issues/34747\n        # *
    https://github.com/go-gitea/gitea/issues/16983\n        # * https://github.com/go-gitea/gitea/issues/21376\n
    \       consent_mode: 'auto'\n        require_pkce: false\n        pkce_challenge_method:
    ''\n        redirect_uris:\n          - 'https://git.danielramos.me/user/oauth2/Authelia/callback'\n
    \       scopes:\n          - openid\n          - profile\n          - email\n
    \         - groups\n        response_types:\n          - code\n        grant_types:\n
    \         - authorization_code\n        access_token_signed_response_alg: none\n
    \       userinfo_signed_response_alg: none\n        token_endpoint_auth_method:
    client_secret_basic\n\n      - client_id: '{{ env `IDENTITY_PROVIDERS_OIDC_CLIENTS_JELLYFIN_CLIENT_ID`
    }}'\n        client_name: Jellyfin\n        client_secret: '{{ env `IDENTITY_PROVIDERS_OIDC_CLIENTS_JELLYFIN_CLIENT_SECRET_DIGEST`
    }}'\n        public: false\n        authorization_policy: two_factor\n        consent_mode:
    'auto'\n        require_pkce: true\n        pkce_challenge_method: 'S256'\n        redirect_uris:\n
    \         - 'https://media.danielramos.me/sso/OID/redirect/Authelia'\n        scopes:\n
    \         - openid\n          - profile\n          - groups\n        response_types:\n
    \         - code\n        grant_types:\n          - authorization_code\n        access_token_signed_response_alg:
    none\n        userinfo_signed_response_alg: none\n        token_endpoint_auth_method:
    client_secret_post\n\n      - client_id: '{{ env `IDENTITY_PROVIDERS_OIDC_CLIENTS_BOOKLORE_CLIENT_ID`
    }}'\n        client_name: Booklore\n        public: true\n        authorization_policy:
    two_factor\n        claims_policy: booklore\n        consent_mode: 'auto'\n        require_pkce:
    true\n        pkce_challenge_method: 'S256'\n        redirect_uris:\n          -
    'https://books.danielramos.me/oauth2-callback'\n        scopes:\n          - openid\n
    \         - offline_access\n          - profile\n          - email\n        response_types:\n
    \         - code\n        grant_types:\n          - authorization_code\n          -
    refresh_token\n        access_token_signed_response_alg: none\n        userinfo_signed_response_alg:
    none\n        token_endpoint_auth_method: none\n\n      - client_id: '{{ env `IDENTITY_PROVIDERS_OIDC_CLIENTS_ARGOCD_CLIENT_ID`
    }}'\n        client_name: ArgoCD\n        client_secret: '{{ env `IDENTITY_PROVIDERS_OIDC_CLIENTS_ARGOCD_CLIENT_SECRET_DIGEST`
    }}'\n        public: false\n        authorization_policy: two_factor\n        consent_mode:
    'auto'\n        require_pkce: false\n        pkce_challenge_method: ''\n        redirect_uris:\n
    \         - 'https://argocd.danielramos.me/auth/callback'\n        scopes:\n          -
    openid\n          - email\n          - groups\n        response_types:\n          -
    code\n        grant_types:\n          - authorization_code\n        access_token_signed_response_alg:
    none\n        userinfo_signed_response_alg: none\n        token_endpoint_auth_method:
    client_secret_basic\n\n      - client_id: '{{ env `IDENTITY_PROVIDERS_OIDC_CLIENTS_ARGOCD_CLI_CLIENT_ID`
    }}'\n        client_name: ArgoCD CLI\n        public: true\n        authorization_policy:
    two_factor\n        consent_mode: 'auto'\n        require_pkce: true\n        pkce_challenge_method:
    'S256'\n        redirect_uris:\n          - 'http://localhost:8085/auth/callback'\n
    \       scopes:\n          - openid\n          - offline_access\n          - email\n
    \         - groups\n        response_types:\n          - code\n        grant_types:\n
    \         - authorization_code\n        access_token_signed_response_alg: none\n
    \       userinfo_signed_response_alg: none\n        token_endpoint_auth_method:
    none\n"
kind: ConfigMap
metadata:
  name: configuration-yml
  namespace: auth
