apiVersion: v1
data:
  ALLOWED_SENDER_DOMAINS: danielramos.me mail.danielramos.me
  LOG_FORMAT: json
  POSTFIX_message_size_limit: "26214400"
  POSTFIX_myhostname: smtp-relay
  POSTFIX_smtp_tls_security_level: encrypt
  RELAYHOST: smtp.eu.mailgun.org:587
  RELAYHOST_USERNAME: nas@mail.danielramos.me
kind: ConfigMap
metadata:
  labels:
    app: smtp-relay
  name: smtp-relay-config-env
  namespace: system
