apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
      - image: docker.io/prom/prometheus:v3.10.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
        name: prometheus
        ports:
        - containerPort: 9090
          name: prometheus
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /prometheus
          name: data
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus-yml
          subPath: prometheus.yml
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      serviceAccount: prometheus
      volumes:
      - configMap:
          name: prometheus-yml
        name: prometheus-yml
      - name: data
        persistentVolumeClaim:
          claimName: prometheus-pvc
  updateStrategy:
    type: RollingUpdate
