apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: gitea
  name: gitea-shared-sealed-secret
  namespace: media
spec:
  encryptedData:
    GITEA__database__PASSWD: AgCWTW3seQhI3hfXjJeTRDKEWj9DrgojY3DZwxal0m2Q1M4Ux4H2Ew2o3+f7eL3NFJTC4fgMexYxU6oS4c6c8bl5d+LXZ7weEt9KaIM1FxGtqYZxgGKwSIZxPPSIbU27J3wLFtCik+3AWCXculs0JDVy9h1EPkxmkzmrQ3IOfcB3R4lHRY7vKa8tS91vxpKbtNMIbi8n0C8SZ8QOHylZPVeHjvWwrF7ybSa9GN+0Rnx8lKvp4XRBOxeqS44LiBXQsHGs6CbkNTOoQb2mxyuy9jM9NKHvH4yC3IsCuamzZlPUjrljkwRYF3YEpsPmH6f64NBMC36vaoF6kGqI3cNirPMKZJc7eeDNLmNb1SamQbLXQKJFvA5XrHl39OLwgBWTy+a/lJdytqh40By7uRbmuXy68R8i6038a+xPVb/KipO5ldpMUOH6f0JkuXyZhDcmi0BNz6HhPfGy7uB1b+dDDBT+TlKxMhdOlvQjj3ECenkvTJagBs585teVkMw6K3/Jdm9SgDRk4XKQehPRig7NNByBIhA2DDqXK3ftRPeeAiZuwtNbb8NMvmNGfp1JDKNf4lnped6LbOmrqtLeX2torqw/UDAnRo5whGt6P6W1i+C+FZvr3Moaor8Wgq4SaYyymcnM5I90hfin7lgKp6TihBSTnhZC6z1mCy6FZ9uCC1I19Hr2B7eh8nmul1jC9kC21MjOmM2f0QQ8Bu9QKP8A+K3+pybsiZ/mjpEhssEbnGRGmp0zchw=
