apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: invidious
  name: invidious-companion
  namespace: media
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: invidious-companion
  template:
    metadata:
      labels:
        name: invidious-companion
    spec:
      containers:
      - env:
        - name: SERVER_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: SERVER_SECRET_KEY
              name: invidious-companion-sealed-secret
        image: quay.io/invidious/invidious-companion:master-5c372ba
        imagePullPolicy: IfNotPresent
        name: invidious-companion
        ports:
        - containerPort: 8282
          name: http
        volumeMounts:
        - mountPath: /var/tmp/youtubei.js
          name: cache
      enableServiceLinks: false
      volumes:
      - hostPath:
          path: /data/invidious/companion-cache
          type: DirectoryOrCreate
        name: cache
