apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: invidious
  name: invidious
  namespace: media
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: invidious
  template:
    metadata:
      labels:
        name: invidious
    spec:
      containers:
      - command:
        - sh
        - -c
        - export INVIDIOUS_CONFIG="$(cat /merged-config/config.json)" && exec /invidious/invidious
        image: quay.io/invidious/invidious:2.20260207.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 30
          tcpSocket:
            port: 3000
          timeoutSeconds: 5
        name: invidious
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 3000
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /merged-config
          name: merged-config
          readOnly: true
      enableServiceLinks: false
      initContainers:
      - command:
        - sh
        - -c
        - jq -s '.[0] * .[1]' /data/invidious-config.json /data/invidious-config-secret.json
          > /output/config.json
        image: ghcr.io/danielramosacosta/jq:main-5231ab6
        imagePullPolicy: IfNotPresent
        name: merge-config
        volumeMounts:
        - mountPath: /data/invidious-config.json
          name: invidious-config-json
          subPath: invidious-config.json
        - mountPath: /data/invidious-config-secret.json
          name: invidious-config-secret-json-sealed-secret
          subPath: invidious-config-secret.json
        - mountPath: /output
          name: merged-config
      volumes:
      - configMap:
          name: invidious-config-json
        name: invidious-config-json
      - name: invidious-config-secret-json-sealed-secret
        secret:
          secretName: invidious-config-secret-json-sealed-secret
      - emptyDir: {}
        name: merged-config
