apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: invidious
  name: invidious-shared-sealed-secret
  namespace: media
spec:
  encryptedData:
    DB_PASSWORD: AgCuppexF9bGQqggJSd77FVmjsxa5XoUHVxEG8yYGu2cB9II+RMZiuU/zo+P8rox/pIdZ3L9Zzxs9Lo2vg/URNYXMBYor4Zhmx7sjW20YLTswgQZn7uGhzwMCP/2WRpfEvb5PV16Xno/iKDgJp9z65onlQDzb+yU2s47XAgiYTXVa22f6n3tvGlXJxYwjw8De2x51NiOs3BAV4fnU8fnYzlD+0fHRWFjz1h9tPZPHsMKvbprxV+cQ1uR94T8dCxRFi5xojPnzYheJLji8/R0YBS5QOzCqrer0TksENr9yLFkwtgu2N04Lpr6ScOiTH6EkfSFDJ8apV5UHBArmDzmafdqKmRdoZkBq5HdAJQygBFO7RtJb4d9nzaPjtYM3GLsqRldRfjYwSUmvz/ad3M+ifehvkUHiAbyJhlwzyYT/H/q9YDZg6hMF+RfMSuQHQCP+d3aI4xXmsjU5+P0B9LsmbBf+mHtppkeqHCmDmJFW/H+8pHzGkLEGQKM3n6YauvbbS20i90nkgDarL2Kwzd9NnL8kAX0GosfQmtpEUWQSaMUpz8VR6M1/jGp5H0lR30TbKFuBg+tRZy1iHPTdfL7q3LjSnvfNmo2jCmw2n+lXbsM28QYI653waLXLm/Ngzrjuzb10ewXV5dTE8MpLhmTJArz92LjxiHES+uRPH6EppRnTlaNyPJ4fW7RQ4+OuPM3LF9fTNtOBSZN3N6SD+oGZcOjzgZOEkIC512otyFco77bmOcIYmU=
