apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: invidious
  name: invidious-config-secret-json-sealed-secret
  namespace: media
spec:
  encryptedData:
    invidious-config-secret.json: AgCt/ahytvt2Ji4FLzq5y/yFCwbG+W8mJxzi3h2agfhtKbTPb65cphLU3vgOcefpUZGek3q6ul+7/+9Qlr70ERs7qi+/rmaj6Nv0QkqpWIDXVQRanXoNl0+3uGx90oWNVkvkODKu+Sdo8JWKjWWd0QAF9TK/mAvCE/KspAfWN0d9e0HXBiaaFgIOj7l7VhdpYEzxJnykjm+SkNODwbnsJDx2M1O4JKB5+yN+PCp4Z58wmckxblPZRqJ3jK8lwfApxfaIBCVyO1PLWMCs9q7HcQR6sOyjRe/MmraWtmTp73xq0RF6FaEwD4lkI6Pjz2j8o2fSFrWZyGc0iWerdbGr9Yxd2PCsujdbEKwjE1Orph5QuZFAe5B2nsb4LKbh4+JZgp3VIif54r+VD8VGyTURxLW1elI+HouW0iBdf0JTcsVgm6JoIk0Nq42Z1tKLeSBpY5Nz9M1zHzN50h+NSSzsy7gb5tjr3l8Jyu5Z+eDehjVpg99he7QfdCIB4BteidS21r1Wci0teZb6jY25rCC1yKfAQc9fupm5Rh4nWvXR4lxG3D9mhdw/+YsnG/xcAXUQsOwW4zSrKVch4r7hP2Zf9lVF8aueZFwqcmFFP+PPVd3llDMYTeC5lrqlBLLFUgzEtwRhiq5dul8gEvyDyZBawJU2HjED8cwZ6r8d+2J19fludjCLkdupFZDMy99q8OHz6DckzVHzCE3JwmSHS/Svs4ZMxUW1dFzqA90quHviiMT7ppT9bx+1WbQrE5iTFFVmKVoiFc5rdmwf6uDGBfiGi4vPD1BwJelP/8+aLenpoX7+tF/d+MseVdJws5G8YX24gAhe2l8no/FxAe/+2aAGgdWmGMeV1o5htuqyMSIxy+IRLSZ9gp9k
