apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: invidious
  name: invidious-companion-sealed-secret
  namespace: media
spec:
  encryptedData:
    SERVER_SECRET_KEY: AgAWw+uTBdImxaaR34RBFIXh1os7sK7uC+CDBRycJUAZ9jmmi5aJLRdWqr5Zi8UdOMzfRxpqgr3YcgVT2p0ZQVRLUO5lbKsebf+ln8DxVkHQRw6fUYfAFbwFIBhkPNFeAYwZixE8y7cFAqVRFD7GzucrItjQjPRXPkYa3PMvcb3aRLFX0yDmUZ7/bYV5JooGqfngTZ/eAINa9ILBkOZYgovvWpGh/kBxiZoazRyo26sC9o6Z3X1anTNLb/Vj2XO2MJkbk5trj2s7EFRDRg6eT+mCqZjrgy2a6OVMatb7xeYMCCvPfOHS2ziUd7EtyJOhNdxhFe+cq5px+mZT06wVLeKijERjpZvbtwcTDPnhsLg7o6pM4r07tRBxNE7wrzLV1id8MSQyJ7rvNfx+TChh9pa3Q7FaK1OwM4RJSXkEhTzC5hWgMeAa/4YawRToKxr85wRW4tCNV3kpnogFBjQAX/HjfF0ueMNRo9zZQJUTvxsapJUhRvCn/gHhEswd2MqroOSbL8JZHF5sE4BadSz80BZPy3NefaOgLeT8PtnK1FlEeM9GIZgPol3pIKSxCnINMeY0VE8VgwmSf0HuyZ6JxlcQu0vPXoMd4RVGg83ecxX1OxggpqC/4WjEupg0VA3m3wRhhOa+dhs2pKtbP8p8Tz0XUllNW95nhAQxtd8xOiKkJYjOyURTa8EaYcSOdNxSOffLC9ySRz12YoYInEdP+2a0
