apiVersion: v1
data:
  BOOKLORE_PORT: "6060"
  DATABASE_URL: jdbc:mariadb://mariadb.databases.svc.cluster.local:3306/booklore
  DATABASE_USERNAME: booklore
  GROUP_ID: "0"
  LOGGING_CONFIG: /config/logback-spring.xml
  SPRINGDOC_API_DOCS_ENABLED: "false"
  SPRINGDOC_SWAGGER_UI_ENABLED: "false"
  TZ: Atlantic/Canary
  USER_ID: "0"
kind: ConfigMap
metadata:
  name: booklore-config-env
  namespace: media
