apiVersion: v1
data:
  invidious-config.json: |-
    {
      "admins": [
        "dani"
      ],
      "check_tables": true,
      "db": {
        "dbname": "invidious",
        "host": "postgres.databases.svc.cluster.local",
        "port": 5432,
        "user": "invidious"
      },
      "default_user_preferences": {
        "autoplay": true,
        "captions": [
          "Spanish",
          "Spanish (Latin America)",
          "English"
        ],
        "continue": true,
        "locale": "es",
        "region": "ES",
        "save_player_pos": true
      },
      "domain": "invidious.danielramos.me",
      "https_only": true,
      "invidious_companion": [
        {
          "private_url": "http://invidious-companion.media.svc.cluster.local:8282/companion"
        }
      ],
      "registration_enabled": false
    }
kind: ConfigMap
metadata:
  name: invidious-config-json
  namespace: media
