apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-books-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
  volumeName: booklore-books-pv
