apiVersion: v1
kind: PersistentVolume
metadata:
  name: sftpgo-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 40Gi
  hostPath:
    path: /cold-data/sftpgo/data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
