apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-bookdrop-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeName: booklore-bookdrop-pv
