apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-machine-learning-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  hostPath:
    path: /data/immich/ml-cache
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
