apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: beets
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      name: beets
  template:
    metadata:
      labels:
        name: beets
    spec:
      containers:
      - env:
        - name: PGID
          valueFrom:
            configMapKeyRef:
              key: PGID
              name: beets-config-env
        - name: PUID
          valueFrom:
            configMapKeyRef:
              key: PUID
              name: beets-config-env
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: beets-config-env
        image: lscr.io/linuxserver/beets:2.6.1-ls311
        imagePullPolicy: IfNotPresent
        name: beets
        ports:
        - containerPort: 8337
          name: http
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /music
          name: music
        - mountPath: /downloads
          name: downloads
        - mountPath: /config/config.yaml
          name: config-yaml
          subPath: config.yaml
      volumes:
      - hostPath:
          path: /data/beets/data
        name: data
      - hostPath:
          path: /cold-data/media/music/library/all
        name: music
      - hostPath:
          path: /cold-data/media/music/downloads
        name: downloads
      - configMap:
          name: config-yaml
        name: config-yaml
  updateStrategy:
    type: RollingUpdate
