apiVersion: v1
data:
  ND_BASEURL: https://music.danielramos.me
  ND_ENABLETRANSCODINGCONFIG: "true"
kind: ConfigMap
metadata:
  labels:
    app: navidrome
  name: navidrome-config-env
  namespace: media
