apiVersion: v1
data:
  LIDARR_URL: http://lidarr.arr.svc.cluster.local:8686
  RADARR_URL: http://radarr.arr.svc.cluster.local:7878
  SONARR_URL: http://sonarr.arr.svc.cluster.local:8989
kind: ConfigMap
metadata:
  labels:
    app: scraparr
  name: scraparr-config-env
  namespace: monitoring
