apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: traefik
    app.kubernetes.io/instance: traefik-system
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-39.0.5
  name: traefik
  namespace: system
spec:
  minReadySeconds: 0
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik-system
      app.kubernetes.io/name: traefik
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
        reloader.stakater.com/auto: "true"
      labels:
        app.kubernetes.io/instance: traefik-system
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-39.0.5
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --entryPoints.metrics.address=:9100/tcp
        - --entryPoints.traefik.address=:8080/tcp
        - --entryPoints.web.address=:8000/tcp
        - --entryPoints.websecure.address=:8443/tcp
        - --api.dashboard=true
        - --ping=true
        - --metrics.prometheus=true
        - --metrics.prometheus.entrypoint=metrics
        - --experimental.plugins.bouncer.moduleName=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
        - --experimental.plugins.bouncer.version=v1.5.1
        - --experimental.plugins.geoblock.moduleName=github.com/PascalMinder/geoblock
        - --experimental.plugins.geoblock.version=v0.3.7
        - --providers.kubernetescrd
        - --providers.kubernetescrd.allowEmptyServices=true
        - --providers.kubernetesingress
        - --providers.kubernetesingress.allowEmptyServices=true
        - --providers.kubernetesingress.ingressendpoint.publishedservice=system/traefik
        - --entryPoints.web.http.redirections.entryPoint.to=:443
        - --entryPoints.web.http.redirections.entryPoint.scheme=https
        - --entryPoints.websecure.http.tls=true
        - --log.level=INFO
        - --certificatesresolvers.letsencrypt.acme.email=danielramosacosta1@gmail.com
        - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
        - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
        - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
        - --entryPoints.websecure.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32
        - --entryPoints.web.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: USER
          value: traefik
        - name: CF_DNS_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: CF_DNS_API_TOKEN
              name: traefik-cf-dns-api-token
        image: docker.io/traefik:v3.6.10
        imagePullPolicy: IfNotPresent
        lifecycle: null
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: traefik
        ports:
        - containerPort: 9100
          name: metrics
          protocol: TCP
        - containerPort: 8080
          name: traefik
          protocol: TCP
        - containerPort: 8000
          name: web
          protocol: TCP
        - containerPort: 8443
          name: websecure
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: null
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /var/unused
          name: unused-data
        - mountPath: /tmp
          name: tmp
        - mountPath: /plugins-storage
          name: plugins
        - mountPath: /data
          name: acme
        - mountPath: /etc/crowdsec-bouncer
          name: crowdsec-bouncer-key
          readOnly: true
      hostNetwork: false
      priorityClassName: system-cluster-critical
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      volumes:
      - emptyDir: {}
        name: unused-data
      - emptyDir: {}
        name: tmp
      - hostPath:
          path: /data/traefik
          type: DirectoryOrCreate
        name: acme
      - name: crowdsec-bouncer-key
        secret:
          secretName: crowdsec-bouncer-key
      - emptyDir: {}
        name: plugins
