apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: traefik
  name: traefik-cf-dns-api-token
  namespace: system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgCpbR1IPeIXhrToiFZwvXAQFGIkNuQ4P3dJoQDrl5C5bkfgC8022YXZFUNckUiSmt0rxEjmMhqYH5HfTikUZnOB6FaxA6WKVoakQRIJSeVbyRMZiyzpQ9ML93j9QT1Io2oPiEadIu6PsyrAIt+o8AygdhCbHDmmo7G7yiVhvYCZB8QeI6p1vZjqDfPDTJ6sR1SaggPGJ3+IikriKIU0ZO7En9zWxjqdE5W+MfxE06F+RKvxN7OQYgCOzpaGAZxw3hgjh55uxBvkfaUWb+VsV2O8Tl5o7q5Gzc62B4oquIeYmvL3m5lE2Ck+4YE8iiHHqlOH/4Z/wEoAD1E5d8B4XE+fGIQcAcUQKidzHiSyI5pAgbpXpJQ0DeeGD3AWBIqiWfmS6ezAZlxY/hfLI/Evf2wjwYUDJm04CYT2ppoNi3jmgEnDKZtdIC3mszQbnMG94w+5R7xZ8pnVqHPdDW81iQzD4xmwwquhypbUkMRnfLiAyFXcjFmrac8nGu0HzUaBV2xqfklC4kni9QEWAfI+ziLVltMwepSRy36d4bmSxWhC2PYlvdQ+ltrZwYPARKLD/Zo3YoIr8OGiqlKdrvIVgD2WSY2nWJKK1Hhmm3xF1cM2aUhFHar/M81mqOwHRbU4TaQm2seeexmvUPS+E5ffPoJJtx8ZotKq9eeCFSXaYLHPZMtyHbYKZOprmO7NvHIQcReOFcF7j73Jc8VBIN3gyD57rMidVeDFozNPpQmEj/vZ4Thj8VydCxbf7SpyG44nGIlhiXa1Sw==
