apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app: traefik
    app.kubernetes.io/instance: traefik-system
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-39.0.5
  name: traefik
  namespace: system
