apiVersion: v1
kind: Service
metadata:
  labels:
    app: beets
    name: beets
  name: beets
  namespace: media
spec:
  ports:
  - name: beets-http
    port: 8337
    targetPort: 8337
  selector:
    name: beets
