apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: beets
  name: beets
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      name: beets
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        name: beets
    spec:
      containers:
      - env:
        - name: PGID
          valueFrom:
            configMapKeyRef:
              key: PGID
              name: beets-config-env
        - name: PUID
          valueFrom:
            configMapKeyRef:
              key: PUID
              name: beets-config-env
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: beets-config-env
        - name: UMASK
          valueFrom:
            configMapKeyRef:
              key: UMASK
              name: beets-config-env
        image: lscr.io/linuxserver/beets:2.6.1-ls311
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8337
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
        name: beets
        ports:
        - containerPort: 8337
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8337
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /music
          name: music
        - mountPath: /config/config.yaml
          name: config-yaml
          subPath: config.yaml
      volumes:
      - hostPath:
          path: /data/beets/data
        name: data
      - hostPath:
          path: /cold-data/media/music/library/all
        name: music
      - configMap:
          name: config-yaml
        name: config-yaml
  updateStrategy:
    type: RollingUpdate
