apiVersion: v1
data:
  loki.yaml: |
    apiVersion: 1
    prune: true

    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        isDefault: true
        jsonData:
          timeout: 60
          maxLines: 1000
kind: ConfigMap
metadata:
  labels:
    app: grafana
  name: loki-yaml
  namespace: monitoring
