apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: grafana
  name: grafana-shared-sealed-secret
  namespace: monitoring
spec:
  encryptedData:
    GF_DATABASE_PASSWORD: AgCqJhlUyEgpKgI7ix34pEhC7TPPOOh+RqVbsD0jHa+dOo3XckZGSiCu+aBf4d1XE1Pc0Ld5w8v58yU7pl0FUwWiAdaRzD6UKQ/OfkWMqWPJHgfU3rwA9CQdhbAYlsR6xslUZDV4IF6bnUB1DD6dTCTIMo3JtgZOe12Q/qjywIPLwLKLuyXU7KVZVq1OgN3vp6oe12Fh9dNRxsF/UJ0AM9SHEVq6wMXVxF9JJjrue20t7zK33jO3+X0SKMjI0ZqIbuBTUtBQx1+EeNzx7MqciJ1EQDJKl02oKQsD7TGiNZg/yZ9ra579qODO7ZvcnkiKP5jmvFleJIVNCZV0pOMcufUOf0tENfnLwWQPY9nLb6IPDWrNu9J6lGypGq2C6xJzETw4PkkWFpqgu6hM3sFjh/2jNTxSPBP+HMixRGZfm5KsGiXMxIM4fPgpsoIeHvt6N19TDWYz9EeGy5ANhpmBZTvN8upfJDkyiPqJ91RJW8SsmltIpzYyzKE+9wwR4HPHme+sctBTp/sEzrTgO/jCuiZ/1e7m6ZPcFxBAIugX189rgyg4ODZWGZ97oFTumZME/FrRn1q1hozHy8fGqveHZG/cjoVepoPPKm4v4MaaVS8lIoJb2Rx+nmXRx2Y8FTWfY6D/yeytTRXHCqZEyOeyFPqUpjUtoufrFUe1AvadTRECIwdwX+SCqo0AGlDZZOnHpd/oAMbBDqculRjnMDWizkB1XAw/H+IvVfP8xWE8BwiNgsjYVsc=
