apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: grafana
  name: grafana-shared-sealed-secret
  namespace: monitoring
spec:
  encryptedData:
    GF_DATABASE_PASSWORD: AgATZNlsz44kakUItvlhwm7VaVJ8ssCs99AJ5ZttdW6wBPtibioVVeE8YT2mwiPi/Dchxg07Awq/RQM8GeWWYJ6GnXBp5vr7lfDF3BEc2AV8irEJF+4I7RTd3gXv6SIK0MCAFnl1oKjUVIjErldkP8k0JGaVPelpBmQn9t8EFUjdj0MdiLPuQ2r9PbV5l+iwUivS5HhiyuPYGyIaQkNh5Rr7z9WLRtvorHXrkQJ00/J9IC8bRjsmaKx/wN01+tN6ei/ttjYVGJjwxSxSoIrV09GZCVkzK4a+degGg7PqnAfoMofzmCSDD8n8CplrlwGfhaQt5aEVq3MgvY0cwizLId6W8g1EQiZOGEwxASr0ukztznchraXzWTFxLn4KnGuUU7G3AEoG0T+tL4tZyk1ageGsQVMWQFJB4FoDZleRd82TfUB+eozspxwLkaXLd+e/KbJOOt1J+9uJty7T4+vg/coFuPv2eItxdXydFuE9/ciVTTtruaGmGEOL2FmxYWaL+mkYR17TMf/DADnGczWw2dPCIPeqjivzt88W9qy3ae9hUJb1IMNidXzxp8HP5tbN23XhnZK64I3e/FFq3UhMQ4I7GUkO2YpByFqrQ0a3oYUHGokgLIZT+iexlWSqLnagvl1gN9sc7c6Gsn3VYEqu/5hYViAlezxRsYgH9hjmgSg8Prupg/PruIxXkA6BrXc+DKJj+9GDcOH+mJanj7misXSINK//7vHDamWUqh55VPT0EXdFFFI=
