apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: monitoring-exporters
  name: nut-exporter
  namespace: monitoring
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      name: nut-exporter
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        name: nut-exporter
    spec:
      containers:
      - args:
        - --nut.username=monuser
        env:
        - name: NUT_EXPORTER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: NUT_EXPORTER_PASSWORD
              name: nut-exporter-sealed-secret
        image: ghcr.io/druggeri/nut_exporter:3.2.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 30
          tcpSocket:
            port: 9199
          timeoutSeconds: 5
        name: nut-exporter
        ports:
        - containerPort: 9199
          name: nut
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 9199
          timeoutSeconds: 5
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
  updateStrategy:
    type: RollingUpdate
