apiVersion: v1
data:
  PGID: "100"
  PUID: "1000"
  RADARR__LOG__CONSOLEFORMAT: Clef
  TZ: Atlantic/Canary
  UMASK: "002"
kind: ConfigMap
metadata:
  labels:
    app: radarr
  name: radarr-config-env
  namespace: arr
