apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: sftpgo
  name: sftpgo-shared-sealed-secret
  namespace: media
spec:
  encryptedData:
    SFTPGO_DATA_PROVIDER__PASSWORD: AgAI2TFuHosz84v2UScUlCR9R7S0PArZXZpz51a844e8isx3SmssCXWf7qyJV7/C56wKNgukVRUPxaAgQI4kZImvi7YZJm++wWNIYagTk4e7ZCK3z3m5LSrhffbZz6+AK5DKz7mgDNmzEGRkO/V72b7KotNAaB0JGUhh5Vdn53WU5VMe75iwkCOWUAtmcDM/5FzYh1/oVe/RD36faXZzmPIvmiY0g6DY+w/WGmjiOzryJnisUh+jxL1k0tk/gN1YSu/iXHgoOYWyAZ53aNBwobMajELtAiuzNS2P8xQqhh8MQtuMdnrgT8hYgEnP3rvrWPeVPow0J0z7D84R2EPdJtTMqerOL64XHrKAMwg818yQYhv+sYfdvUfHG79Fc8319oa/7WM3skcp9TYPj5UCtq1spdZJrCYWx1M0lE/6ajfTrfuBM1WYHUxUZmjFke0J8uByCGWDcS/O6jvk/zGlAruli2t75MyKhw8y+qiFRx+yuL/OtjAZRuTKezT1fNpbRK3jPdDp53AtuWe8J9CDV0VkL1ogY3DHVgORtHOq2oNaGJL4FhaK1T/ijNVbiXuq9WVcQcjmyscvPxLdDD4wS9xlonqI111m+cFBdF5qjff/GHHb0f1fAiy/TNpfLmaggk/X0G2BKJekv7/7xXP3F7tx/5SR1XLoujKdyu84eLF7aPOpP20qtmAb9zipPL1opadbtvvWIVRe5FSCX4Bu9GyJZUlCkf3Bn8g1aZEHxr390ceBMPY=
