apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: sftpgo
  name: sftpgo
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sftpgo
  template:
    metadata:
      labels:
        name: sftpgo
    spec:
      containers:
      - env:
        - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_ID
              name: sftpgo-sealed-secret
        - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET
              name: sftpgo-sealed-secret
        - name: SFTPGO_DATA_PROVIDER__PASSWORD
          valueFrom:
            secretKeyRef:
              key: SFTPGO_DATA_PROVIDER__PASSWORD
              name: sftpgo-shared-sealed-secret
        image: docker.io/drakkan/sftpgo:v2.7.0-alpine
        imagePullPolicy: IfNotPresent
        name: sftpgo
        ports:
        - containerPort: 8080
          name: server
        - containerPort: 9219
          name: metrics
        volumeMounts:
        - mountPath: /srv/sftpgo
          name: data
        - mountPath: /etc/sftpgo/sftpgo.json
          name: sftpgo-json
          subPath: sftpgo.json
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0
      volumes:
      - configMap:
          name: sftpgo-json
        name: sftpgo-json
      - name: data
        persistentVolumeClaim:
          claimName: sftpgo-pvc
  updateStrategy:
    type: RollingUpdate
