apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-create-user-sftpgo-sealed-secret
  namespace: databases
spec:
  encryptedData:
    USER_PASSWORD: AgBhnDVOSXA7mX+DI8TrzNCARGQ0XRoluBDEmBGmQc2fYRy3/AYgp8/j8Y+G9CGihW1HVZQuJgfarg4czRi0LYa/Z2fAaEmwQrrOFOhLmspSCAtWRslU9c4QRZzYLgB7nMfQ42I761+Bbpw3zLc0T4nIuJNAs6NE46SDKkymfYfouqp9rzoqHy44MhHnHZ9HAdLft/GgJj25TSMM5o3/dcWMXZlgiSMp6pTSGN/Sfwy3GqPlesZ1+Gb+1a1PyL+WEculsWTQ9dyLaeG9yiW3/vTUKnqlrz3f+MWz768z0O21r2l4K1LQSUrjV9rkVjqeBiw1qOYour1MD36zyC1c9QkA6QkpemtmzEd2z+QlaF9zjkFOE2mYkzur04N8p1gAjvFGiuQbwrbEmS/HeEY5IVKFPeD0FFtaWgykBiCoMNypeMI38+FVGCU6fgaWA55aiYwzHf3BFwG5ZH1QvLjHbs+D+YVOdXESZ/woUPmdT+Md11Pqd0smA5OBcdnfmQescr1NbWM7atwd/5u3JXFh1Jeuh8eGughUp/6EMxhdXn4n+h/7maev7n1kOU2nNBCwcpi7s1lhAWSwep69x5ABMfeuOVTJbVieJgQMlfKWoO1hvpDvVKtBIxOCewysL0aRi7IsmgwpE2e8sC2bemoJSkUzOj5tE1HQd37mU1ybvyjC0H3AHH7FysRaqCL7J3slP20tJttAyMw02NBTfL06gw3sBcVpJBBFQ8G5WZKPdEMPh5Dn++0=
