apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-backup-sealed-secret
  namespace: databases
spec:
  encryptedData:
    PGPASSWORD: AgCCJaz4hpiQenZ6ZmVGIfTGS4EeiQpuAlX6kecyDZFkOj+/yw363WfaYKdhmC+QcEskhqQmvRSQCWuy3+SUBwAksyJcro9IicMT9lwU7B1YQtM8wNZk8MAnJzofsd1wG1EGRd5ytBYlSY6wxWtFbbJotR2DU28o2lim4u/uherl07aPZ4a9Oyg7nhowoQW4Z4d8786hzXgZXdJ+N9ZZJglHI2U1C9BNjlHHUIidi+rM4EHKhUMq27I5OVby/c9A1ZwqW6Kuhq2iEaH155VVIN9u5MnOxRD14UN9mO2oO6vEaBOHao5/1OBTxJ6ZmkgoklGjXrgQi+hLMUv1lK4E+TwXCay3eU9ye7oec2JNGYZQRacre5eoMAkT8mFUC5Y+yY9BT9C3k3pkYR7lBQjr96DxS/aZ6o81eum3fQK0Zfy89OqzF+qHlPjdFHarAgrY1nWYbtv3+RHyjV+CfEPNuyiboFto1CCfFypHQHIeDOwUXYDke0cd3mnarzZMU7i1nMJPyj4m78MIIoWhIk00oVshcYrgPgheeKUUqzdO1zJjR5GxHEN9a0MuEIfAMA6CmQ9GbzVFv73tazxj+nqWsGLEhV20joKHG/ETjQz/kuQe0e/U5gUvDWqJqziJvjWNenlsBbx4J8DYHVZ1tJ4U+xRWuodqoiGKIN0FXyNJi+OopNKfYFgMQ1R1eMji9cm/qIorwXrMdRIblfjrvnF+G9VRZKDBygYqAzpf6wsZ1kq7M+0eBUc=
