apiVersion: v1
data:
  config.json: |
    {
        "$schema": "./immich.config.schema.json",
        "backup": {
            "database": {
                "enabled": false
            }
        },
        "storageTemplate": {
            "enabled": true
        },
        "passwordLogin": {
            "enabled": false
        },
        "oauth": {
            "enabled": true,
            "autoRegister": true,
            "buttonText": "Iniciar Sesión",
            "issuerUrl": "https://auth.danielramos.me/.well-known/openid-configuration",
            "clientId": "{{AUTHELIA_OIDC_IMMICH_CLIENT_ID}}",
            "clientSecret": "{{AUTHELIA_OIDC_IMMICH_CLIENT_SECRET_DIGEST}}"
        },
        "machineLearning": {
            "enabled": true,
            "urls": ["http://immich-machine-learning.media.svc.cluster.local:3003"]
        },
        "notifications": {
            "smtp": {
                "enabled": true,
                "from": "NAS <nas@mail.danielramos.me>",
                "replyTo": "nas@mail.danielramos.me",
                "transport": {
                    "host": "smtp.eu.mailgun.org",
                    "port": 587,
                    "username": "nas@mail.danielramos.me",
                    "password": "{{SMTP_PASSWORD}}"
                }
            }
        },
        "server": {
            "externalDomain": "https://photos.danielramos.me"
        }
    }
kind: ConfigMap
metadata:
  labels:
    app: immich
  name: config-json
  namespace: media
