apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: immich
  name: immich-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: local-path
  volumeName: immich-pv
