apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "3000"
    prometheus.io/scrape: "true"
  labels:
    app: immich-exporter
    name: immich-exporter
  name: immich-exporter
  namespace: monitoring
spec:
  ports:
  - name: immich-exporter-metrics
    port: 3000
    targetPort: 3000
  selector:
    name: immich-exporter
