apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: monitoring
    repoURL: https://github.com/DanielRamosAcosta/nas-k3s.git
    targetRevision: manifests
  syncPolicy: {}
