apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocd
  name: postgres
  namespace: argocd
spec:
  destination:
    namespace: databases
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: postgres
    repoURL: https://github.com/DanielRamosAcosta/nas-k3s.git
    targetRevision: manifests
  syncPolicy: {}
