apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocd
  name: mariadb
  namespace: argocd
spec:
  destination:
    namespace: databases
    server: https://kubernetes.default.svc
  project: default
  source:
    path: mariadb
    repoURL: https://github.com/DanielRamosAcosta/nas-k3s.git
    targetRevision: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
