apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocd
  name: navidrome
  namespace: argocd
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: default
  source:
    path: navidrome
    repoURL: https://github.com/DanielRamosAcosta/nas-k3s.git
    targetRevision: manifests
