apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    client-secret: AgAQdxdzSpOaxMUJ/BftV90ir3T9wtXW5t2oVUSsQHpooOK7moBLp6YhABQrVz6ca9izkjWHABeAWzzBD7uQlpU1FiOwmwiJ6QtJvUHTEIIF/DjlNhG9Hxb3fVB2Sq3RHEyWBxw+otS4QJPD2foIU1zbHeV3nK6MAaQdosftHG/GncsxkCITXVAq41pYE38wziThGlRDVCf4ifLKI9TqOOhJnvVh89D88WzQq0FQny1rEuXllpudQ26QC5lLFkLi7zBKV1I0JiYZzOybCuWV+OLwJSneDfyDGTqc3+yEKm0wZ+3S5+hFKN9AbTgEeG69s9j1yf5pUfyf9I7XWyWuxpJ/4TTNyexcX4KU87nGFhyRhT5dGd40bjOIGUkLiVHtfisOT+jaZus9+alCPdpnHRRs09OqWtwz2O1Z3Zv7CTQHqLECpJJ0wQ2r+u1FiayEki1tq49fneyrp1LUgz/pG2KU6/qdfG3deEE8NzjJFCDbovAjNSIUP0NJElITKVjw6KZi8u10T8mIQeQ8nLaDqoc/spT3MaENfySvT476JrbBVEWGuEHtiPSTEyDHzo79SVj2UO2IW1s7Q0QcNncP2+AsocC8iq8RCy4/gwwc4bhIANxbhDueueMAyaMx4X2LPTARZOo+bQBPmZSrl2lZJQEpGN/iDjNe8IrvTf7ZOuGlt/qcGtvdSHGhVtP/Etk3JWDTE8nzyT2nywJO8MjEAFTAz7tdlSRuNW66kPCEGdec1CxnPs4JrTKq2r2jOvUHdLNmHPH0a4k/UlX2/xj1oEDeQ1p0rI/JLbs=
