apiVersion: v1
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  _;

        root   /usr/share/nginx/html;
        index  index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location /tiles/ {
            add_header Cache-Control "no-cache" always;
        }
    }
kind: ConfigMap
metadata:
  labels:
    app: squaremap
  name: squaremap-nginx-conf
  namespace: games
