apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: couchdb
  name: couchdb-create-user-obsidian-sealed-secret
  namespace: databases
spec:
  encryptedData:
    USER_PASSWORD: AgBVqY+4S+OOZJ+LTI0TuivzpyNS2il8vuls5v7GTtnfpvqyeI6b9lbi3bBe+N7TYMn2pThFXFyyHX5Vfm7dIb4Og0qhwG0SPq+tPNypNnMsDElSCNLE7vZsHzdbB4BbE/Ic4PXpageLJdnDy8SGHjzgtETldeCV5v5b4QwkedTh9lz3SEVqP7yLCRhLHCFnsWg7jwkOJc5bBcIWthj4JlJGRcFcNBmNciRTpgZAc8KfjXBuCFKuFrb+UWd+LNSe6irEX5eySPHZ23pOz8fBTyJgpe+yzLruSJ1zjWZ4NeBEjrOsorqXbznX+OLlbiSSL/M8Xu/VeZyDqYt+Pm56iLFf9Fu5GwMyxgTkEwLBocKO1WKrw9L4UKfKBjKOr6+zcv7PLWFQvhwm0wcZ5421hFcvpdmw9xH6/TnkkDky8Xqck5xSMXepDEGo2u+9r5MaXa6oqJ1WmiufgSwEJBxQJkGwiBRiSEt+BhwE6GwQRjUKmDCuvtbRRvpT2BECISnTn6Es4Pb2yQNeQOBlTKylNh2PIXhA+F3nAo7XpZ/FrmympTM6/ylqj1S5Pcpf9QrYw+CPdUg5LtNVqoScmce7PZfB+rQP4qT4Ke93pH9+DwRho3BWTb9CFQYCe/3IwfbQAk0EIVjYhaMgOwcDIHxQ8ogxJL7zmguczMJoVFMizj2/UQgnNONwUzhnpR+yXYx85JQkOkrxEbY51TxyYa2RGczHKWcQ5M2F4OTbkEg+c1MokQ==
