apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: cloudflare
  name: cloudflare-ddns-sealed-secret
  namespace: system
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgAy5X2HwZPiz95Z6PcaP9MhkBm9jn5s6SvSXxxyUxyzgSodBzn7dzfPJmtzihLHvHhj6f/gN88lwOsHUZYOMsBuPPQyGwruEaTrNr58x2c60oXtc4+m9IcVdTkCqvn8Qjoqfqvd/Cy+mln6YBq02EfAIMBL8F2yjjr+9Ai3BV/PXogN7Ypttd+coD9+CIA6KZYr96oSeWDsNgayWtkK+vOnzJN/6nrcDvLgKqEAlGkj5riFOF+vuHgfAFkJ3LJ4gJWZIxi7jPYDgMtwUbrD5pEdocgZg8otpUdMdJvopldlAap2LTnV5cKhGl8ZDrEiG7m3xJqB32c9rIQYUNq3lCpazMEzITyNDFWKQxfMKIGtjqNgOkYz8bV0mivc6ead2d1GJXp0bW9JDmi3kp/nJ2Q0wmemUt60B+Yk4WNA2JQJx6CZf5/IQu6RlilohNZdSm064muBacXo6dAoDLjxmJRHWT6IoH/Pgh3jriX0L+K9SqaJBGQTNhLc0jC861xJCZYlklf6CPCcmHceQr0wHFkbonoLzM+NGpqU/dlO94N2mqpCuBmTe3yNCYoPh10DjQNsb8lex2rrigOcknAis0lXYPqxAB8QhBkYnt1mZD7bEbEuw1fYMN5bUo8F+PyFC5pBkxHCDU+gplBE+OHLJU+H8HwbAvFretK96VV85uIkg/o0652FN6k7RBuf9sHJvqfEv++6HjqMxQ9M3IQMQYzpZOYPnqk69t19DehhxwNWAF+lB+a4IHBT
