apiVersion: v1
data:
  DELUGE_LOGLEVEL: info
  PGID: "100"
  PUID: "1000"
  TZ: Atlantic/Canary
  UMASK: "002"
kind: ConfigMap
metadata:
  labels:
    app: deluge
  name: deluge-config-env
  namespace: arr
