apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: deluge
  name: deluge
  namespace: arr
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deluge
  template:
    metadata:
      labels:
        name: deluge
    spec:
      containers:
      - env:
        - name: DELUGE_LOGLEVEL
          valueFrom:
            configMapKeyRef:
              key: DELUGE_LOGLEVEL
              name: deluge-config-env
        - name: PGID
          valueFrom:
            configMapKeyRef:
              key: PGID
              name: deluge-config-env
        - name: PUID
          valueFrom:
            configMapKeyRef:
              key: PUID
              name: deluge-config-env
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: deluge-config-env
        - name: UMASK
          valueFrom:
            configMapKeyRef:
              key: UMASK
              name: deluge-config-env
        image: docker.io/linuxserver/deluge:2.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8112
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
        name: deluge
        ports:
        - containerPort: 8112
          name: web
        - containerPort: 58846
          name: daemon
        - containerPort: 58946
          name: peer-tcp
        - containerPort: 58946
          name: peer-udp
          protocol: UDP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8112
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: data
      volumes:
      - hostPath:
          path: /data/arr/deluge
        name: config
      - hostPath:
          path: /cold-data/media
        name: data
  updateStrategy:
    type: RollingUpdate
