apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: mariadb
  name: mariadb-create-user-grimmory-sealed-secret
  namespace: databases
spec:
  encryptedData:
    USER_PASSWORD: AgCWYzL3j1qr1olnvqCielYQMmywYN3mX56VSmU1VUteyMlm5v6jv3vD0gxa1Ol/UheU2qVjYL5QXKcAvKsrdIaLgySwYTOEHwO8rmMkJs1vFqsjQ1sPUG+3iSgskyuXgoZz0sUUIIE4pZv+Zb8H3zOddrmC+V5iiKJiabbGxG8y9HVjAh76LDpUNlmloYsXka8nJBtidk2Dvd0pUvq/K+RLUFAD5BO8crHeHmnx0gQyznejMr9gd4ApGGSRianX37cWUBbkIdUjSh3RN7QYNO2HC6dPCIvoQLNf35LtCCnx4At4Rbvt1v6PpKMTrHf5Pmb2WLDiAroBpOW3SgxSh45GRMUURprdV2+ZhEU6SpaYPg4TTB14umRPMAPY3bTG2kYxVqO8z8jecrEfSc5DSXeh/ihl/jVyOwbFeOokMWQlWZUnpuAWbpxWofvRx/V1LQVgPopfaoNYPFFYWBB7DDPfs5CmQXtgvS5F3eCeCouJHw6p8scP148ZMmmbhzvdoVSApc9hG53qj52G1zSNlEJi0TBzQUMIkrDdO6kse5aJ85v31T+U2PVTvpfSAR+/ujYUHvewn/xERE3S04cUkA1KNMQUFczKGY7JrFYwEOOo+vbh+XYs+daQlvVV5aCPnQACN7IxL4T7LzGkT9wu0iTAvXh5qc2N1UpX1JZmAw3rTAvbbtspZb08aLAcUb429YLUlt1xlETrh/1isBa6Jlsg3zY7tgGXSo+USgFhNyXUchMjhO++jtcxiUWBuQ==
