apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: mariadb
  name: mariadb-create-user-booklore-sealed-secret
  namespace: databases
spec:
  encryptedData:
    USER_PASSWORD: AgCbKu/wZHjRUc/xwhYSusOTZtmlY/XHed+mv9PYklSZ+oaxkwUwTIT5a4NF56u24nR7fdbG9aWiS7HcRs2wKBopBABZ5xL/Ga/XThoYCq3MYr8CygLyHQ5NJazVP0hqJybmMF5T1cSY6jwd53akFZ3Sw7K8QuRbg8s8pWc8JurPxidU2mGY99D4HeYqjBwnjki9fXM9qJQ9+67PIe2qOXR1FghL8mHSNPWf1za+lcgMQdaQ+a9tl2Eh9eYsU7eJXaraHivtsaD6V4/gGat1itSkGqeeGj129wodOGUsmrGQW5bJ03usvHveZHMS0vVoVdntz4IKEgUIOgzR69JYM6ItFtnfXMwgK1SEmiw/gZP5iYL7L3if30Ner7X9tr6US/SaEXpjeccNTryLGyvOk0IT29aa84AkKhYWB0obKiHRUwF4OoUoqosK95j5ZSPb2zOmakIISAmdik0xMyl37idIPnutkaaYXy6jKdsP1meeHyr8dZR0kM2P/Sg6f4GZWUS0WPgbJsCoyji/eKoWDAUz/KGjRJvrbY76oEDLY9gpJjsL2vDmlKdfHI30ThFt+kdhcgYeUI60S4ZD9XNCCTVzRUNouCZjruY8Kvw+c7RWFEaElpvepnmxrqE9hfjQa9xq4VbDQSN8zitmllnlLIntBQYiUfCVkg0TgQ07YpemwPvIDvxfNYfL3ReDowx6lRRREnQ0f4rgoIl6Qx4M04oti/mXccJQUaG/5WHUQzzC8XjI8Mc=
