apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: mariadb
  name: mariadb-sealed-secret
  namespace: databases
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgCci4Vwp+bTJQyesGdSoqaaYOTfIabjvcGedNiRBmDy8lbfVqruSV5WU3IavKioqQHUojCSf6D6vHZtdTaixwyEM4+YYlFkCHIPFAGcEcCrAmeaquC7o72r9mjxsmeWwujZ+QUVSk4RB59INWEejKBplD0L2LFpwzvUtKmJpGgGsDsTh+64BZM9/CNZFmSC5ljK5gF7QTyrMFe3UKI4RvSj6Pi4T+zCtJhsk7Pi9d1nHUf1wASwkGzzb97Xl7cMmRwwmS6ZG95g/DBJ202awe9S+fwVVJnVi0oq32QrzyGnIjaxb0GsjA5A8iE9SaSO+MkmCpcCqlV1SgGLjtlVWngMc1xbZJ9HGBxcEJZm5HTBduo3QLrfFffc7/Zd9DmSIX/c4vIBNcsA7a7d2Msxx9/9T8XRxe1/SWVxMlt3+pH2VWogq6iZz2Vk98Ao78F/rwZdVdGMtyNAdxCPqN2BKEJ8iNqWnZMgGRllQfAndeQAA1px2riFRvg+zycH9vv7UBxvYfGAYdaPzcyAfySRh8KTv+vlNsx6H9QQKqvr5sGTp8TS2p4fqImBXVntAaul6fJUN0yVv5ji+Bp7pdaOtCT/dJE5gtxsyzLFMWdHLqn2Uu2EBZJqOdr2fLvkRMkBHXKcYgsXmuLKgJxr6qDa7iCPKoNgjNT4BbeeghD8nGuclOHKb2ZLS/A4accMzkYkvMTFxwuXqSf6uwokY+xEj4j/ywC2JFEdA8My0zguyAkRv5aI33w=
