apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
    name: mariadb
  name: mariadb
  namespace: databases
spec:
  ports:
  - name: mariadb-mariadb
    port: 3306
    targetPort: 3306
  selector:
    name: mariadb
