apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mariadb
  name: mariadb
  namespace: databases
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mariadb
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        name: mariadb
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Atlantic/Canary
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: mariadb-sealed-secret
        image: lscr.io/linuxserver/mariadb:11.4.8-r0-ls201
        imagePullPolicy: IfNotPresent
        name: mariadb
        ports:
        - containerPort: 3306
          name: mariadb
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 3306
          timeoutSeconds: 5
        startupProbe:
          failureThreshold: 30
          periodSeconds: 10
          tcpSocket:
            port: 3306
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /config
          name: data
      volumes:
      - hostPath:
          path: /data/mariadb/data
        name: data
  updateStrategy:
    type: RollingUpdate
