apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jellyfin
  name: jellyfin-cache-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: local-path
  volumeName: jellyfin-cache-pv
