apiVersion: v1
data:
  slskd.yml: |-
    "debug": true
    "directories":
      "downloads": "/downloads"
      "incomplete": "/incomplete"
kind: ConfigMap
metadata:
  labels:
    app: slskd
  name: slskd-yml
  namespace: arr
