apiVersion: v1
data:
  DIFFICULTY: hard
  EULA: "TRUE"
  EXISTING_OPS_FILE: SYNCHRONIZE
  MEMORY: 4G
  MODRINTH_PROJECTS: squaremap
  MOTD: §c§lE§6§ls§e§lc§a§lr§b§lo§9§lt§d§lo§c§ln§6§le§e§lt§a§la
  ONLINE_MODE: "TRUE"
  OPS: Duning
  PAPER_BUILD: "65"
  PAPER_CHANNEL: experimental
  RCON_PORT: "25575"
  TYPE: PAPER
  TZ: Atlantic/Canary
  USE_AIKAR_FLAGS: "true"
  VERSION: "26.2"
kind: ConfigMap
metadata:
  labels:
    app: minecraft
  name: minecraft-config-env
  namespace: games
