apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: minecraft
  name: minecraft-rcon
  namespace: games
spec:
  encryptedData:
    RCON_PASSWORD: AgCyKC24Oft0DZXLESOTuHY+n3cBXYgJDD50C+dtWGtIcrxlcvZY7jXnzt5OQW4/i8GGJZIj1SETGPEMpK0TwdtDFM9M+c9+cFyQDPVGnsiaSFmpSK71hz+F2ybiIV6dQgOlLJGjL30BCLYh28hU43pV/rv3mFqf24bkfqrUtu5pyTqi62oasuwotdwRKumjSrQp43+1nzsq1cQqJciie+Lmb86OD5O18+BOJiPvZq+dZmqnw0jZLxENmn6RbeJs/3hFKaiKyM27fqyEzuKwBXlL68RrcQmYuulJUko66z1iQ6einh9evaszSq1JMlPYvPtcKvd1w5Lbw+nBmz7Dayw6UDTsEh2LT5UAwChytbOxoWNyLJcbGYOj0E9b4b5rbfyL/Hotkb8IQNeyF+Htk19aVBEHq97LU0SxeSZEiT1clIc/ASr89i5zLTEhLSpWwAiwe+A9DphPC9djdtcxO7+crizI8JBmfyj/ukCR0jYabU6VYiq8/5vwnTbH9VwgUY7Tb40GtZyG/3FsOwMQXlFwwe6k8SO0DBhQUXhloyl1s1LA6+x1Cz71gqBwzozBfddzDX1Bmsj5o+yzT2jcFQaqFCN7uqRn82TIGgmOKuFLn3HiEPzbHiEuptLQENO62kTKEU5zqFQbee7l8frhcY3GtDPggvNxVBqKrSsJHRQOSCeaiYFOzPrQsFHpA7YFbosuExeWLczQLSS8kV+xpXYKcVcHHPnXa58qttFI4+MnzA==
