apiVersion: v1
kind: Service
metadata:
  annotations:
    mc-router.itzg.me/defaultServer: "true"
  labels:
    app: minecraft
    name: minecraft
  name: minecraft
  namespace: games
spec:
  ports:
  - name: minecraft
    port: 25565
    targetPort: 25565
  - name: rcon
    port: 25575
    targetPort: 25575
  selector:
    name: minecraft
