apiVersion: v1
kind: Service
metadata:
  labels:
    app: lidarr
    name: lidarr
  name: lidarr
  namespace: arr
spec:
  ports:
  - name: lidarr-http
    port: 8686
    targetPort: 8686
  selector:
    name: lidarr
