apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: lidarr
  name: lidarr
  namespace: arr
spec:
  replicas: 1
  selector:
    matchLabels:
      name: lidarr
  template:
    metadata:
      labels:
        name: lidarr
    spec:
      containers:
      - env:
        - name: LIDARR__LOG__CONSOLEFORMAT
          valueFrom:
            configMapKeyRef:
              key: LIDARR__LOG__CONSOLEFORMAT
              name: lidarr-config-env
        - name: PGID
          valueFrom:
            configMapKeyRef:
              key: PGID
              name: lidarr-config-env
        - name: PUID
          valueFrom:
            configMapKeyRef:
              key: PUID
              name: lidarr-config-env
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: lidarr-config-env
        - name: UMASK
          valueFrom:
            configMapKeyRef:
              key: UMASK
              name: lidarr-config-env
        image: ghcr.io/hotio/lidarr:release-3.1.0.4875
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8686
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
        name: lidarr
        ports:
        - containerPort: 8686
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8686
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: data
      volumes:
      - hostPath:
          path: /data/arr/lidarr
        name: config
      - hostPath:
          path: /cold-data/media
        name: data
  updateStrategy:
    type: RollingUpdate
