apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: valkey
  name: valkey
  namespace: databases
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: valkey
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        name: valkey
    spec:
      containers:
      - image: valkey/valkey:9.0.3-alpine
        imagePullPolicy: IfNotPresent
        name: valkey
        ports:
        - containerPort: 6379
          name: valkey
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 6379
          timeoutSeconds: 5
        startupProbe:
          failureThreshold: 30
          periodSeconds: 10
          tcpSocket:
            port: 6379
          timeoutSeconds: 5
