apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: valkey
  name: valkey
  namespace: databases
spec:
  replicas: 1
  selector:
    matchLabels:
      name: valkey
  template:
    metadata:
      labels:
        name: valkey
    spec:
      containers:
      - image: valkey/valkey:9.0.3-alpine
        imagePullPolicy: IfNotPresent
        name: valkey
        ports:
        - containerPort: 6379
          name: valkey
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 6379
          timeoutSeconds: 5
        startupProbe:
          failureThreshold: 30
          periodSeconds: 10
          tcpSocket:
            port: 6379
          timeoutSeconds: 5
  updateStrategy:
    type: RollingUpdate
