apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gluetun
  name: gluetun
  namespace: system
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: gluetun
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: gluetun
    spec:
      containers:
      - env:
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: OPENVPN_PASSWORD
              name: gluetun-sealed-secret
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              key: OPENVPN_USER
              name: gluetun-sealed-secret
        - name: FREE_ONLY
          valueFrom:
            configMapKeyRef:
              key: FREE_ONLY
              name: gluetun-config-env
        - name: HTTPPROXY
          valueFrom:
            configMapKeyRef:
              key: HTTPPROXY
              name: gluetun-config-env
        - name: VPN_SERVICE_PROVIDER
          valueFrom:
            configMapKeyRef:
              key: VPN_SERVICE_PROVIDER
              name: gluetun-config-env
        - name: VPN_TYPE
          valueFrom:
            configMapKeyRef:
              key: VPN_TYPE
              name: gluetun-config-env
        image: ghcr.io/qdm12/gluetun:v3.41.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 30
          tcpSocket:
            port: 8888
          timeoutSeconds: 5
        name: gluetun
        ports:
        - containerPort: 8888
          name: http-proxy
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8888
          timeoutSeconds: 5
        securityContext:
          privileged: true
