apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mc-monitor
  name: mc-monitor
  namespace: monitoring
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: mc-monitor
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        name: mc-monitor
    spec:
      containers:
      - args:
        - export-for-prometheus
        - --servers=minecraft.games.svc.cluster.local:25565
        image: docker.io/itzg/mc-monitor:0.17.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
        name: mc-monitor
        ports:
        - containerPort: 8080
          name: metrics
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
