apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonarr
  name: sonarr
  namespace: arr
spec:
  ports:
  - name: sonarr-http
    port: 8989
    targetPort: 8989
  selector:
    name: sonarr
