apiVersion: v1
kind: Service
metadata:
  labels:
    name: slskd
  name: slskd
  namespace: arr
spec:
  ports:
  - name: slskd-http
    port: 5030
    targetPort: 5030
  - name: slskd-https
    port: 5031
    targetPort: 5031
  - name: slskd-slsk
    port: 50300
    targetPort: 50300
  selector:
    name: slskd
