apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: postgres
  name: postgres-backup-cleanup
  namespace: databases
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: postgres-backup-cleanup
        spec:
          containers:
          - command:
            - sh
            - /mnt/scripts/postgres.cleanup.sh
            image: busybox:1.37.0
            imagePullPolicy: IfNotPresent
            name: cleanup
            volumeMounts:
            - mountPath: /backups
              name: backup-storage
            - mountPath: /mnt/scripts/postgres.cleanup.sh
              name: postgres-cleanup-sh
              subPath: postgres.cleanup.sh
          restartPolicy: OnFailure
          volumes:
          - hostPath:
              path: /cold-data/postgres-backups
            name: backup-storage
          - configMap:
              name: postgres-cleanup-sh
            name: postgres-cleanup-sh
  schedule: 0 3 * * *
