apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: postgres
  name: postgres-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 40Gi
  hostPath:
    path: /data/postgres/data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
