apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: postgres
  name: postgres-backup-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /cold-data/postgres-backups
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
