apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: postgres
  name: postgres-create-user-immich-sealed-secret
  namespace: databases
spec:
  encryptedData:
    USER_PASSWORD: AgBblNptSGzE5/nalD6fzdZdbAVUXoexvYibAs6zHdeqywGTJTU2PKqHy0PmiJda/j0u+FKHrCdAEGe5pVFNLp7aWfoQqdmM1RdOPfT3jTpk50Ygl6YNf1YlsmX+vw0gWovGkXhBKS4gXfDtlJB2GQNYCunfXA2SlQHW377UFstY4h2C+kjoZ0mX3etrtqHZ3ppIBUL7mR7WTP5kq2/aVrviWJhy0DiTEZR19w7yYNP1umCdju/ZPeu/b3+XLr/LaMhHgsWAqwDR7W4Dz0Fp9XEPj8qvaheYaOzA62j/hiJTSHqTRJMPZst3T1/5eru30IvsmCXjPOWhsZD6UNflSCUHsX4NQSMPHzYhA3n+KCvS8t6SGWuH/0mGjsAB0xPkhNew+5QWf6ZwNLZIe1GBgW//f9F4kJoIGIzA4duOFSAeuL1zC2pY8J07tatAqVfJg1kaaZ30QIYezGwbyU251gijoLPj8ksqZYmq9CPpY53ICgvQGW95U3xqI6F3/EksdTEYiFTyDLMXYYO1RaWMqD3kN5SiFijMMcpJpkfa304S60nujQWo5ejjwxHbBVQkOftZayPk6CVy7dbtnLl1RcvaDYpJOGcl8Pq3QDIALbhTeph36/pxw9B5SpzwepjWsGqFWgs9bbnom6xVCG1dYxNPT3LjNx7cMam8JVg3GamlHWLy9hz5W8U3JEg+1Ci6zO3z/O/i4nn26CNFpOLKOtllR8PHjygbdcjre10PklXr2WBCxx8=
