apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: postgres
  name: postgres-create-user-wger-sealed-secret
  namespace: databases
spec:
  encryptedData:
    USER_PASSWORD: AgCW8UfICmIsBABu/jjx5M8GgqSjAvArjBq0M5sCjHlBnS26nD6wG0tRnb0V8+y3Ys3bR3MFYuej8lLBbi/64IVdJ87W+1XG/+fMOyqoAThT+eKsVXCsP4wd2IQU73vd+PDQigGc20v3VoBaKXqe7ioZ/hFckmHX+kQDdbd+e4TQzcINJcUcOZmjHuy3r28eC1a6lRB5Tm3M6CCutPh3fuEGh8FnFx9PTZRQfpnKLa345eKe/wWaxDLPZ984jE4LIfXtX4hnAJ29NCJ+vvmwauBcGOpLj9krsA7e6KnTUZTPfgEyak5gMbL8Lg61LDFixAf99Sjle+obc/+4+iwy/0ctDygXW0QusX77SmyivUb/FNND+86pFmd42LJl4mt9Xr4P3EmAVdNZ+7f9dp3G7h0UkzY55sA+hUMfSThI7Z+36aN13rHIaM7o3MQYNzZRm4p1KlgxTTsH/FabXMGY/mqyf5MYnf9Sq4uWusguTPLZNd5PScVPKtMobeP9W3TQ1lEoklm5pM+bSXYbXvY16d323lND/njYfBa7iDD0zEkcb/XV+X0H4Xob7Ic8bmDa7KuWC8nyW+ZH9s1tgu5v55yJFeMpwZqnjWAvNZ3on0bVJHCSNeZt3w6rIO7Oe65Ct3hp0b/BAfM+is2yuiuGwtuxdUnGfe5hmyox6ieCsoIbqF/tB2mhFO+PIHD7Dl5RX7r7r8tjR8czfArxGFqU+KqyWapksN48pd3veYHAqdTRfw==
