apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: postgres
  name: postgres-create-user-authelia-sealed-secret
  namespace: databases
spec:
  encryptedData:
    USER_PASSWORD: AgBmXTBl3OCGSkHqBna0bE2qFGAxwNQ43kySlk01QTROWwl/1SYnwubHps9ikcEAa6jB2HiOl3ddyM+dK5mxMPkTVvXKYgbcMb/yFvaFs6Jr5hhN+xvN+Pvy3koozlYK9Iy6FpHqoI0tEYYCdQR6C0S6/Kt3qYyqqQ7GQddJ7C8UVZKkNvrNMaC7ZjAH5mDHd3CdspwxiI+GOBhvjfUlnBoS/xm81NkVRV+VuuPA8Jdx+jIvVfrBG+evp4PMh03s2CVoQ8BoNZy0Gov077/sRYHD61X99szb6cuPW6MqIIN0c9yQZqdU+QNhGLnpfkdPKoNBLrWBSDz6S3JYrJ8C2Ooi1VeHdfjbaTsqJeyFq6w+iTHa/eoyaJ2zVMKfvHF8ytGoWTOhNruYUmCEmdGUkH3UjIEQ8L/GmWNNQqPfyvYOGUvc1LgmF/JgBZZLTfPewGnAMYElsbjehFhYcQqGduIwrxgddSPHtP0gRfUqsKINbIpihjyqninyj9mq7/tlauFvfeXY1GMdlTMi4+7/U92RdxW11mAbQUaLNWycP/86NDPMWwbI+ukgblCKUkYyni1aNd3W/+HGDrEHU6Y19SHUqByz/ZAiVGFrOH66j5L2AjzYxHr8iOjH8s+A+9xPLfBfwSnzVgOHw03YcvxY8IfGlD2v//O9t5+ILtgyNRqiBaYC2230j1OWzowTmHgpKnBJCE6M4iS/DzburKNWM8aeEoVVBkVEruSMoL4tBjYpgIviTfg=
