apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: postgres
  name: postgres-create-user-gitea-sealed-secret
  namespace: databases
spec:
  encryptedData:
    USER_PASSWORD: AgAEaWosR7W8T1B9x4YefgGl2gM4DRj1g1ST7nD3CO+q5RATH2OY0AAAmEf7OCMU41ztigaYwgdemtQ0eQkYH4Jl9HhFi2mkA3QXSYEWyOiAwQOfbXDTt7fzl6we2zJadOXb5SfPVk6flAjRcu9u3eMNgBONVGo175ygY/Jl+DyXafA3Qk5+aCWkzldaPBfRP7gn2M9LZ+Z7ltp1qOYobF4mAXXkTI+DYz3UEt6kxMHtFXg4WeNjUATV3ELCBCVpQ3HIKPDijF9zxqJWI1wWrMVe6/kDFpngtluaOqlvK5SqkEISJffg0Q+dfKRkN22jAWdTqq75hOHTyPqlbozBNRjwISgf4HfnQ5WMuRveNCmsRf713rDfbRISxwv+6HjCb0jWciibjvRP9X5PSK8Lel/oBxINFbDd3j/xIDiunn3j1J8rK3/upzmSE2/w5nHA1NvvHJywF3WYabphCMQxZLKervsvgC9N8Cz0VqdVrCPR38yt/FHtU4OY7IvDmoteSRHGllWGANGfkIAyaaZEfRajtYnMHyPLEFZFwMGiLFHem7+Cnny/eD0XatRt/V3M7yehsyRP9dXxR+YMjF2+d0D1XRD5dlmk77sc6uezuMsXE197v1oAwauJMND0dU58JElTqGhldLAOERMAT8nRenHLsbIazTT2o90Ho4kVRPLoHEEj92WT4CD74g2CbztByGpPalba+dCNs/0YesAMUHzzUv0vvqteI9UOv2PVOSBzOdO4Os4=
