apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: postgres
  name: postgres-create-user-synapse-sealed-secret
  namespace: databases
spec:
  encryptedData:
    USER_PASSWORD: AgCoFK97nMOqrX1O/t1QPX2ksF0i5KAvl92q3FZ4wYGNQLkpei9IBUkOhgXVUOX31ZYjyBs07gtDpUEFNnjkLwkjYZg4HhvnKXdT9DshmMxIJNMXrKS0o9e/TZXwGOQuE/loDlubiIaVN2WVb/MC/0OCVC9uGOZQ4ew+eXbuT2k00A3aatudIrnGFUZLWQczTZNAtrvrby9MDPJQWXKRv5dnDALQqstalTR2+BF0VDeT5JDWCvS22bYsRtciIhrqFL3+2b3E+DDRNWOoW+w62Fn8ETL2CXvBCWung8E2N3FrwfJidPbWqBKN8eK8E7Vbp3+2qnouE6UqzYGn7bMhJW7e8WtcZZEHosP07wXUBResSXtlZDYdjJRw/tdgs5qof1pSHfALjLwzvTO0XNasiCgXQEqdbSxtv4ctUCKvRCK9h7LUfPGtRtjl7iENUhLFiwKdY+wbwDIg5fHAcv1lxUtxj7/kEAMFCbyKm+RSomfIbwnhRt+yHfVDM5fMEAtPZFiUCW1l+3Yil3Te7zXAHUpLy0aACAgOJfowep3fXZHzO9VE6CDpFLupAguxdeWnfAtMHy23AH8VN1wEktBShZgY8pad5XrYqxzancriEHxN9KjfBx3Z0v20t928cL1/xUuUOyr8OoUyKmqHRlfiincmP9mR+gWPY39xvjyKDXPbrsmRGJ5iodUm8PpKAPsjFqLGi9J5AB2KGAFzLaVrkXSGkhMCozxjjQqyVluf1Ll3NHYGlgrUiSiiwhdDaeU6CN5om7KrVGlhqIAMo5o2MSzv
