apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: postgres
  name: postgres-create-user-piped-sealed-secret
  namespace: databases
spec:
  encryptedData:
    USER_PASSWORD: AgCrqubqAOW5nTtB2dNPa95LmYbMUVRjQwjXMTtPWtIfXzMDmpvfMzlYfIFMzBUY3Y13hMGowOnW7eANw5nXrreUYhodSL6T949/rHJDeFE52WTcn3ffXSwXKObCJGcglGTh4Xk0LnPUXZtxqwAAkYbxqEcsrf93zYeE1fH4KkbfXCZpleWyUsihj6kQQkIO+Qi+Il9b/G8iJrlk7zQ2jX2UIxoOD9IUX0FZ/QgKyvj2P9Vt9gZggWh8ubJgqachqVjGfjCaz0wd+Sz48rCM6WNZHOXxasZm2QoLD7cTtR8C31e4dMTSqOjnNLvWV3fEFFxMhUKDo0F1uWDTzrRtTEZ1VM0hkPE9FrG25xIGOZTgffOu8iF82Kw7G6HRCirUgIGEG2kgHY97JRuNCKcARq+T5YYVB4VQbji90QqnhczkXHNvCOOPLI0kVweAp4UsuTj5wt/1ELy3sa9lKXrZTq22j726JkgfuIb9CfD/+uMURIXkLFAvIpoanWhy629taNylsc03QVKAL3W6TBAE4Vry76Hca8OlyGp0KQjVro13VL4eQTnGplui8hWQP+T9dG0yjvoo3R2kxXO9Q7GtetUL638iaYMmdfVO1wnHZrHcPNNfjGBFLfguzZr5bE3ypZRv9gYkWPXjLcm6uLJtNshjfsom3B2VSaq1JLC79M3rh+WtD9CPVFmALjwuh1Lh1SL6E/XaE+bqxsSQEf1x/OEudoWlAEIH6YwHD99dcyfKKt9Rs/g=
