apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: booklore
  name: booklore-bookdrop-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /cold-data/booklore/bookdrop
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
