apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: booklore
  name: booklore-books-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /cold-data/booklore/books
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
