apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: mautrix-whatsapp
  name: mautrix-whatsapp-db-sealed-secret
  namespace: communications
spec:
  encryptedData:
    DB_PASSWORD: AgBdlG9pHZx2/FsBNG5Q8JuWXL1D2+0MDCB5NKvbSfG3SzaqPDFtQMwgyShhcJHq2J6cfEPXHlaRwBOnZU5e1ic5bii2O7d6c5z61rGTswQ/Z1RfmdYk9Nr7vBaHFk+hu63XjdLfmigx3zZWpW050Py9vNRnAcqmpAnvu2nmNYxJlAgcvmEdGeVG9dNkmQY8ZP5LQ+nyr+oyToC2OcWrIXI9hdDN6GUbwQaEVWHmeVFiAAE6kqwl8Fq1P4P7U0jDepqcGpbP1PWwYIVIxejG8zRZr2Ln/Avv3Q6pouRmxhEn4IY1XOKivjayueniYtqa2ec+WtFscayUt3xDRaRnWQd5dqmznRShXz4sGspngMs2EYOTeb+i6ueBA1Ihd7/F/JAVZRSdWr4n9Xbqy4mA4NyTVMZh5dVDX4Ui0zW+hfhj+YdeFbf3DeqeDxS2vg4mJvM2tZ83sT5GH3Zs8lF5gp3LhCcXssezVMZdtd/KZp1PFKaxk1a3bAl2HGTisusnSmJWZ9BFj46BgsJv0fR2ng9gtcRagVBxJxHcq4r39QEf7ijpay2kHCBw15olssM3CRrMoqllqgUtHQhklXWqqqZaLTZJWFLInGDA3UBoqgx1SpLODDr8o2y3nuaxcSNbkie/xXw9swwCua2tvcC018wmrPrxcQWmyTm2mHDfmvlW2U/k+YiVbW4YWCqo7pDxyKO8bc7+6z6UMXF10zXNqD5NgVbzbxJBhIfE46UEnpBsPOIxLIuviMjT+3ZRRx3WjLRuqNLSIocp3UPj9AzooHmJ
