apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: mautrix-whatsapp
  name: mautrix-whatsapp-sealed-secret
  namespace: communications
spec:
  encryptedData:
    PICKLE_KEY: AgCUFW08u1VFHdVQp//Dklx3kLIxj7WNIRmLuUlV1/nSDWwrq+ZehwbOQR1pl5cppXX7l751Oq6eOH7fh94rIpyjCNF1ixI0O+OIwVw86nmkIO2U9CPlG5CO/fRy9T6rahFVWx3ZFf338zi//nt2iGVARFx8fkGx9Vzx3UYvwPWrZjAfp1th9nvExja5lztoGBc0xKPvp/ZO8MxdhE5LnSNK/h5Ktdh3lHE3MPt8PqQQcDoySYOcu/X6leeq2PMO6L8pBsEXmGszyqkwnKOqzpiOmrHcr6SxrQ3gLvNVSG2AbhfS08oGOalLMKS73/c42FSJj/yRLkAKokFlhw89Gv6P9M0JPkiecsDICKRf+fJJ9qSsiR+cXf8QHwq7Ql3MrNt5F4cOZys8LoDB0Bs/+9NYEwysF5lfEgJMqlKCge68ZHbRAmjnyQ4jyyV+LpySiSBxdjNpy6MmGt9Z2oBolr2DfkRjIzF/+Y5y0buELAun449ZMxMSGU0EIC1ZaoFqmLeWFKB/v7l3ZtSeDwPYZ2zHE0hw3ZRdtwTVEt887VpLFhf432EjkldO2sr84YEm2Q0Ttg3/F+znIawtRUAgl3ohy0qA16lEU6uYjllzaG3hzCS1qTi9JYc4V4GesbXR4khXZSwPdGHBdVuD4JsrMiiEL54wloz8j6D5+xyvmEft5Sjco00r2Ob9PkTGGU909u+LZp6o0rT2B8tnzBF7RK2isOKnNREXDs/x7VBvT+1Tc0crHdMHnOBnKm9Gyqzva6Yo5pGItMfC5+1kXlyaYh36
