apiVersion: v1
data:
  console.yaml: |
    share_manual_decisions: true
    share_tainted: true
    share_custom: true
    share_context: false
kind: ConfigMap
metadata:
  labels:
    app: crowdsec
    app.kubernetes.io/managed-by: Helmraiser
  name: crowdsec-console
  namespace: system
