apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: crowdsec
  name: crowdsec-console
  namespace: system
spec:
  encryptedData:
    CROWDSEC_CONSOLE_ENROLLMENT_KEY: AgB5R//njrUr8ERAXE+zrqi1KReJUmBvjaGL/ikWAmTscbCKYs7vfj7aSb3Acb7PYH+BppzWeY3gFaj+UlnHTKAXltKLjQanaMlr0k6YBS2xVjgUuRbjQoq3vEkOqj69i8dOkWhhDf0aHOZP5OfyOZOyL+CFtUPaOt3MUI1Xwzt/c7ucea+49cJcPuf0cQFdW+0zIauZeGinuQKvt/7vWkeEwiruPs/Qsr6ScfH9MQDEWVfv5u4blRUE9jwzSHh7+ao/L9O0Jj4bPI4XJf9zZEszA34aYWrz0bDKbsYL66/2vC7HLb9HxVqpZ3zGBLnCbBJfPn+GBbcxB8Ek+6Oywe5ahSUApe5iYQBU32GB18U/EzREKFEW6Lgi5nB4PhMA0OhyNRiROkA04bKNw8KqCDsdwByxgPxmBtjgQuwrjtRdYW0/SJeEsaVw5gj2IyUmVhpo9j4TtnnvHfiu9JuBvX5F2hYMRMR/hjT7ZzPXO1mvMkS+YC904ewOgPe3W3Y6rvZMwN8l453KZBn+ujOHQr906Br3XmGulkr7bF7apKUWNfKScOt2Z0205gU00zFfB+rRhgZCR3dyBxBm+NmiVdvk0AKkGew34Qr5Vv/WySj6MUS/uWcDPqg2BLkyel+VF1zBHUHAX5Pijpj04VGOq4LOqLGN8w1gRqK1PLXnt9OjUwLHBOAjm6KyzavyLIGmeEK+TGkYlFsXFLqLDCl/pA0jvGtGwmAvWq8O
