apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: crowdsec
  name: crowdsec-postgres-password
  namespace: system
spec:
  encryptedData:
    USER_PASSWORD: AgBzzrD/3/eZ56vce2SgFWjYNOZLNSjrTr1HenRM0Q2ZSae0u+wx6YSeA33TC6BUWUDytxnpAELHLV+S8+wO3t3w9nTuHCue4U7ahIF/NNGXmtcK/w4xBg/AvKGfskGEQEoy/araMsqbpvyx6RJKMBGNnM/uphvM8KeMykBFdbOV6lw0j11e4EhfSQVmx2lpcZvhx94RzXUDLZR/CfjQboJMcM0jSYiLmSPha9bHvcairOg+Zraoa5/23ZNWTNfSQcFUXjzaCHTbm9D8QAljVUDfNcubry2uzRXyEWsvbYqiXTV14WhEySXsmcehU6Z8N3NeopnQMb8lhUQnKR+Bh3BfIKGoNnt4dTSXwOBD4yjYlwCibnEKwYhcqCdMDTRCvC1o17Zq3hVeCnX72QUWyRyj87Ru1/b/+mZbQFQxPGeOBUzrs2zWZ68Kr2JAzjkqgNL+9+ML9TkjYFlMbsZ6SY8k0pS3DWGPDK57A4HYzbSFls5MdzLU5CCvCtPpGYwtNDWaYGvnPu7LcglUMna5Ru0bIvcMcKQsXr6NxcUy7oDmRZmOXEmE8FHcH2jmt0DfSfaMFmg7UiNJYm7XU6kZ8QEtx8bODBo7EtnFqRxVFllrTWS1z+oYHb5RA+dwb3DS3qMTj+BrS12L89Wu2lsNm8ABaCIf+EBG2jPozvmO+JB4yt2M+K6mFN8F2Urf8toAwUlEb0O0yuBzpsSHjnEc/ECBcvMyLrmr0bJg6f3qHyAltP1ekRiqpVAV
