apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: crowdsec
  name: crowdsec-bouncer-key
  namespace: system
spec:
  encryptedData:
    BOUNCER_KEY: AgAaG2YGx0TB4ZmZ0iM0DSG+mn4RMRUAFzP4iu//8O4XCFtQ4GjXDyGNA7mssNwXt/zyUYaqrEjNvYhHEXAR9CYugDamKbcrWATviN+qZdGaWZadOs6gAhE8BLrfGr3lCWgBUjDN3SvwMRWnMXp97VZKCDxR0booTqawEnH4IXlNdwkXH1cJfhvgo6tKlMAX3HEL1QOS8g8UqEFCQttqh/F5IHGJ9/5s9AaOo5N8GJQQ5vxA8nUCzevMYEqR8kOn0Osz+onSMwyCWACPmhXa6t02sM75V/NVqv8AIHu06nRfAShFzvRvlBKahQegsUDC5NrCiL+etwIIgoMyqMRWSWgb9H4Csxr2oQTrYzDpY/peQqlDlqpVEvhXF49DCv+zY99D88uGFr2+L+6rLPL2vas+ed/SQvYrWdJz+yaEjX5Fl6zjSfPwf77unKojrGKgl42tjkfDf7KTDRpB37nO8bZjAsUKkAcIHfS2UEO3kVgUa82sawARVY94XYftAiiL+hmkW7QKNj+zJZMMe85d9OVnKAEHvsa6+GD9FDixD4v9wg8WkPl8rPbnhvPvrnc+fss9lTrNZ5eqePB6/2K7FF+RwTGL9wb6knXfVdqhT9Ik5UlV4aZrLiBPlt5Kqnx4LQtZUxFtJcgL1KZMQG7iepK7rHNhVkn1wUJskKz5m6+4g36RWonuTj1zs/SObezS0IO9m4foycklX4UzLTAjkqr56TdeK450V8CHEqAt03idSIu8TOaD7MI=
