apiVersion: v1
data:
  csLapiSecret: eClQKitVWGlAR2pWL3R6RXJqJk48QihQRV5OdzVQNT5Bbz9RL30/eUlyXyBBL3k4JlUvVlNfJE0tP3IyLnUvTA==
  registrationToken: ZkFDZzZnYnl1Z3ZsQlN5TFJtUTVRc3BWNkJpREZRNHR2dVJucXZWampoUW05U2ZE
kind: Secret
metadata:
  labels:
    app: crowdsec
    app.kubernetes.io/managed-by: Helmraiser
    k8s-app: crowdsec
    type: lapi
    version: v1
  name: crowdsec-lapi-secrets
  namespace: system
type: Opaque
