apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app: grimmory
  name: grimmory-shared-sealed-secret
  namespace: media
spec:
  encryptedData:
    DATABASE_PASSWORD: AgACkPTBP+YHpjcIUJz9lktJY71zHsjuUPerwxI9CMerwYyf4Le4Y4g5SxktiHEsmVODqNCibLQW2IOhR+0/IoyHnykQcwB8EYv+0gFsjceS6uKnx6crAQe0Qu+l7Hz8oixCHliJXtWMCJXXmfx0Je/BB41klgjhttcThqENhRBwAwpIlVkzU7iSe01/5psMVNJU3MPP4kVZFE7NehLlGbIpsheGUdn3SYgDEeweYbFf7Lg1Z7Y+Wc6XePvUq+l5wpHAT3GwxAFOl8QlneElbcAl7o9JDDPHLsHl32FI18JDVK3Bs6L+D0mf3G3QVvdtL9BvaQvx746zKGbYJv5Kg/nAXCKUkWGLEYN35CiUNAKu7BUCXHdRChUBBCksZpZgMBSj/JpJ9uyELygG18nOpBVhFmOoQ2i90Wc+BdWq2WGvmf77GLPFYrs2kXYaaY5T0KhqrAPuNeLrjlLQ91IerIOhyF/t6dv0Mr8iprNF32iquNy/2KoKOpyalzGUJ0dzKM8f4xn2zbWuXtxmrBX6aCVk+I5Q7DkiZ+4apqWP1qyK7SWxSu8VrijXo5tjnn4R6OwhUsmiibv/Y4urZyKkcKarPqng2klVWBIr+VuA6Je80iF+G2mKiMSfr1bWQy6Byub01kluVO0ZEahE8SPvPb+j2odlbBnIQ+roZtyGTzoxO9b0PD+yOUbcfWNR+FrpFTgfmodRbpmdK2LowvlYAPglHw3oRSjyZ3/ioekgp5cfitfU0RJI0kBcsCnmKA==
