apiVersion: v1
kind: Service
metadata:
  labels:
    app: grimmory
    name: grimmory
  name: grimmory
  namespace: media
spec:
  ports:
  - name: grimmory-server
    port: 6060
    targetPort: 6060
  selector:
    name: grimmory
